-- =====================================================
-- FASE 2: CRIAÇÃO DO BANCO DE DADOS
-- MIGRATION 003: TABELAS FUNDAMENTAIS (GRUPO 1)
-- =====================================================
-- IMPORTANTE: Esta migration cria tabelas base que não têm
-- dependências complexas entre si. As Foreign Keys serão
-- adicionadas em uma migration separada.
-- =====================================================

-- 1. TABELA: people
-- =====================================================
CREATE TABLE people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(150) NOT NULL,
  date_of_birth DATE NOT NULL,
  cpf VARCHAR(14) UNIQUE NOT NULL,
  rg VARCHAR(20) UNIQUE,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(20),
  address VARCHAR(500),
  type person_type NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para people
CREATE UNIQUE INDEX idx_people_cpf ON people(cpf);
CREATE UNIQUE INDEX idx_people_email ON people(email) WHERE email IS NOT NULL;
CREATE INDEX idx_people_name ON people(first_name, last_name);
CREATE INDEX idx_people_type ON people(type);
CREATE INDEX idx_people_deleted_at ON people(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para people
COMMENT ON TABLE people IS 'Armazena informações gerais sobre todas as pessoas (alunos, professores, funcionários) do sistema. O campo "type" define a classificação fundamental da pessoa.';
COMMENT ON COLUMN people.first_name IS 'Primeiro nome da pessoa.';
COMMENT ON COLUMN people.last_name IS 'Sobrenome da pessoa.';
COMMENT ON COLUMN people.date_of_birth IS 'Data de nascimento da pessoa.';
COMMENT ON COLUMN people.cpf IS 'Cadastro de Pessoa Física, único para cada pessoa.';
COMMENT ON COLUMN people.rg IS 'Registro Geral da pessoa.';
COMMENT ON COLUMN people.email IS 'Endereço de e-mail da pessoa, pode ser nulo.';
COMMENT ON COLUMN people.phone IS 'Telefone de contato da pessoa.';
COMMENT ON COLUMN people.address IS 'Endereço residencial da pessoa.';
COMMENT ON COLUMN people.type IS 'Classificação fundamental da pessoa (Aluno, Professor, Funcionário).';
COMMENT ON COLUMN people.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN people.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN people.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN people.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN people.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- 2. TABELA: schools
-- =====================================================
CREATE TABLE schools (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  address VARCHAR(500) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(255) UNIQUE,
  cnpj VARCHAR(18) UNIQUE,
  inep_code VARCHAR(10) UNIQUE,
  student_capacity INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para schools
CREATE INDEX idx_schools_name ON schools(name);
CREATE UNIQUE INDEX idx_schools_cnpj ON schools(cnpj) WHERE cnpj IS NOT NULL;
CREATE UNIQUE INDEX idx_schools_inep_code ON schools(inep_code) WHERE inep_code IS NOT NULL;
CREATE INDEX idx_schools_deleted_at ON schools(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para schools
COMMENT ON TABLE schools IS 'Gerencia as escolas municipais e suas informações básicas.';
COMMENT ON COLUMN schools.name IS 'Nome completo da escola.';
COMMENT ON COLUMN schools.address IS 'Endereço físico da escola.';
COMMENT ON COLUMN schools.phone IS 'Telefone de contato da escola.';
COMMENT ON COLUMN schools.email IS 'E-mail oficial da escola.';
COMMENT ON COLUMN schools.cnpj IS 'CNPJ da escola.';
COMMENT ON COLUMN schools.inep_code IS 'Código INEP da escola para integração com Educacenso.';
COMMENT ON COLUMN schools.student_capacity IS 'Capacidade máxima de alunos da escola.';
COMMENT ON COLUMN schools.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN schools.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN schools.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN schools.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN schools.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- 3. TABELA: positions
-- =====================================================
CREATE TABLE positions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para positions
CREATE UNIQUE INDEX idx_positions_name ON positions(name);
CREATE INDEX idx_positions_deleted_at ON positions(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para positions
COMMENT ON TABLE positions IS 'Define os cargos disponíveis para funcionários.';
COMMENT ON COLUMN positions.name IS 'Nome do cargo.';
COMMENT ON COLUMN positions.description IS 'Descrição detalhada do cargo.';
COMMENT ON COLUMN positions.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN positions.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN positions.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN positions.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN positions.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- 4. TABELA: departments
-- =====================================================
CREATE TABLE departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para departments
CREATE UNIQUE INDEX idx_departments_name ON departments(name);
CREATE INDEX idx_departments_deleted_at ON departments(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para departments
COMMENT ON TABLE departments IS 'Define os departamentos da instituição.';
COMMENT ON COLUMN departments.name IS 'Nome do departamento.';
COMMENT ON COLUMN departments.description IS 'Descrição detalhada do departamento.';
COMMENT ON COLUMN departments.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN departments.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN departments.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN departments.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN departments.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- 5. TABELA: roles
-- =====================================================
CREATE TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  default_for_person_type person_type UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para roles
CREATE UNIQUE INDEX idx_roles_name ON roles(name);
CREATE UNIQUE INDEX idx_roles_default_person_type ON roles(default_for_person_type) WHERE default_for_person_type IS NOT NULL;
CREATE INDEX idx_roles_deleted_at ON roles(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para roles
COMMENT ON TABLE roles IS 'Define os diferentes papéis de usuário no sistema para gerenciamento de permissões. Um papel pode ser marcado como padrão para um tipo de pessoa, sendo atribuído automaticamente na criação.';
COMMENT ON COLUMN roles.name IS 'Nome único do papel (ex: Administrador, Professor, Aluno).';
COMMENT ON COLUMN roles.description IS 'Descrição detalhada do papel.';
COMMENT ON COLUMN roles.default_for_person_type IS 'Indica se este papel é o padrão a ser atribuído automaticamente para um tipo de pessoa específico (Aluno, Professor, Funcionário).';
COMMENT ON COLUMN roles.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN roles.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN roles.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN roles.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN roles.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- 6. TABELA: permissions
-- =====================================================
CREATE TABLE permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para permissions
CREATE UNIQUE INDEX idx_permissions_name ON permissions(name);
CREATE INDEX idx_permissions_deleted_at ON permissions(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para permissions
COMMENT ON TABLE permissions IS 'Define as permissões granulares disponíveis no sistema.';
COMMENT ON COLUMN permissions.name IS 'Nome único da permissão (ex: view_students, edit_grades).';
COMMENT ON COLUMN permissions.description IS 'Descrição detalhada da permissão.';
COMMENT ON COLUMN permissions.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN permissions.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN permissions.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN permissions.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN permissions.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- =====================================================
-- APLICAR TRIGGERS DE AUDITORIA
-- =====================================================

-- Trigger para people
CREATE TRIGGER set_people_updated_at
  BEFORE UPDATE ON people
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Trigger para schools
CREATE TRIGGER set_schools_updated_at
  BEFORE UPDATE ON schools
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Trigger para positions
CREATE TRIGGER set_positions_updated_at
  BEFORE UPDATE ON positions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Trigger para departments
CREATE TRIGGER set_departments_updated_at
  BEFORE UPDATE ON departments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Trigger para roles
CREATE TRIGGER set_roles_updated_at
  BEFORE UPDATE ON roles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Trigger para permissions
CREATE TRIGGER set_permissions_updated_at
  BEFORE UPDATE ON permissions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- FIM DA MIGRATION 003
-- Total: 6 tabelas criadas (people, schools, positions, departments, roles, permissions)
-- =====================================================

