-- =====================================================
-- MIGRATION 026: TABELA ATTACHMENTS (ANEXOS)
-- =====================================================
-- Esta migration cria a tabela para gerenciar anexos
-- (fotos e documentos) associados a diversas entidades
-- do sistema através de uma chave estrangeira genérica.
-- =====================================================

-- TABELA: attachments
-- =====================================================
CREATE TABLE attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type entity_type NOT NULL,
  entity_id INTEGER NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path_url VARCHAR(500) NOT NULL,
  file_type VARCHAR(50) NOT NULL,
  file_size_bytes INTEGER,
  description TEXT,
  uploaded_by_id INTEGER NOT NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT now(),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para attachments
CREATE INDEX idx_attachments_entity ON attachments(entity_type, entity_id);
CREATE INDEX idx_attachments_uploaded_by ON attachments(uploaded_by_id);
CREATE INDEX idx_attachments_deleted_at ON attachments(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_attachments_file_type ON attachments(file_type);

-- Comentários para attachments
COMMENT ON TABLE attachments IS 'Gerencia anexos (fotos, documentos) associados a diversas entidades do sistema através de uma chave estrangeira genérica.';
COMMENT ON COLUMN attachments.entity_type IS 'Tipo da entidade à qual o anexo está relacionado (ex: school, person, student_profile, incident, school_event).';
COMMENT ON COLUMN attachments.entity_id IS 'ID da entidade à qual o anexo está relacionado.';
COMMENT ON COLUMN attachments.file_name IS 'Nome original do arquivo.';
COMMENT ON COLUMN attachments.file_path_url IS 'Caminho ou URL para o arquivo armazenado (pode ser no Supabase Storage ou externo).';
COMMENT ON COLUMN attachments.file_type IS 'Tipo MIME do arquivo (ex: image/jpeg, application/pdf).';
COMMENT ON COLUMN attachments.file_size_bytes IS 'Tamanho do arquivo em bytes.';
COMMENT ON COLUMN attachments.description IS 'Descrição opcional do anexo.';
COMMENT ON COLUMN attachments.uploaded_by_id IS 'ID da pessoa que carregou o anexo.';
COMMENT ON COLUMN attachments.uploaded_at IS 'Data e hora do upload do anexo.';
COMMENT ON COLUMN attachments.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN attachments.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN attachments.created_by IS 'ID da pessoa que criou o registro.';
COMMENT ON COLUMN attachments.updated_by IS 'ID da pessoa que atualizou o registro pela última vez.';
COMMENT ON COLUMN attachments.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- Foreign Keys
ALTER TABLE attachments 
  ADD CONSTRAINT fk_attachments_uploaded_by 
  FOREIGN KEY (uploaded_by_id) REFERENCES people(id);

ALTER TABLE attachments 
  ADD CONSTRAINT fk_attachments_created_by 
  FOREIGN KEY (created_by) REFERENCES people(id);

ALTER TABLE attachments 
  ADD CONSTRAINT fk_attachments_updated_by 
  FOREIGN KEY (updated_by) REFERENCES people(id);

-- Trigger para updated_at
CREATE TRIGGER update_attachments_updated_at
  BEFORE UPDATE ON attachments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

