-- =====================================================
-- MIGRATION 029: CRIAR TABELA SYSTEM_SETTINGS
-- =====================================================
-- Esta migration cria a tabela system_settings para
-- armazenar configurações globais do sistema.
-- NOTA: "key" é palavra reservada no PostgreSQL, então usamos aspas duplas
-- =====================================================

-- Dropar tabela se existir (para garantir estrutura correta)
DROP TABLE IF EXISTS system_settings CASCADE;

-- Criar tabela system_settings
CREATE TABLE system_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" VARCHAR(255) UNIQUE NOT NULL,
  value JSONB NOT NULL,
  category VARCHAR(100),
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  deleted_at TIMESTAMP
);

-- Índices
CREATE UNIQUE INDEX idx_system_settings_key ON system_settings("key") WHERE deleted_at IS NULL;
CREATE INDEX idx_system_settings_category ON system_settings(category) WHERE deleted_at IS NULL;
CREATE INDEX idx_system_settings_deleted_at ON system_settings(deleted_at) WHERE deleted_at IS NULL;

-- Comentários
COMMENT ON TABLE system_settings IS 'Armazena configurações globais do sistema em formato chave-valor.';
COMMENT ON COLUMN system_settings."key" IS 'Chave única da configuração (ex: municipalityName, municipalityLogo).';
COMMENT ON COLUMN system_settings.value IS 'Valor da configuração em formato JSONB (pode ser string, número, objeto, array).';
COMMENT ON COLUMN system_settings.category IS 'Categoria da configuração para organização (ex: general, website, dashboard).';
COMMENT ON COLUMN system_settings.description IS 'Descrição opcional da configuração.';
COMMENT ON COLUMN system_settings.created_at IS 'Data de criação do registro.';
COMMENT ON COLUMN system_settings.updated_at IS 'Data da última atualização do registro.';
COMMENT ON COLUMN system_settings.created_by IS 'ID do usuário que criou o registro.';
COMMENT ON COLUMN system_settings.updated_by IS 'ID do usuário que atualizou o registro pela última vez.';
COMMENT ON COLUMN system_settings.deleted_at IS 'Data e hora em que o registro foi logicamente excluído.';

-- Trigger para atualizar updated_at
CREATE OR REPLACE FUNCTION update_system_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_system_settings_updated_at
  BEFORE UPDATE ON system_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_system_settings_updated_at();

-- ==================== POLÍTICAS RLS ====================

-- Habilitar RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Política: Todos podem ler configurações (público)
CREATE POLICY "Public can read system settings"
  ON system_settings
  FOR SELECT
  USING (deleted_at IS NULL);

-- Política: Apenas usuários autenticados podem inserir configurações
CREATE POLICY "Authenticated users can insert system settings"
  ON system_settings
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Política: Apenas usuários autenticados podem atualizar configurações
CREATE POLICY "Authenticated users can update system settings"
  ON system_settings
  FOR UPDATE
  USING (auth.uid() IS NOT NULL AND deleted_at IS NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- Política: Apenas admins podem deletar configurações
CREATE POLICY "Admins can delete system settings"
  ON system_settings
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM auth_users au
      JOIN user_roles ur ON au.person_id = ur.person_id
      JOIN roles r ON ur.role_id = r.id
      WHERE au.id = auth.uid()
        AND r.name = 'Admin'
        AND ur.deleted_at IS NULL
    )
  );
