-- =====================================================
-- MIGRATION 034: ATUALIZAÇÃO DE ROLES E CRIAÇÃO DE POLOS
-- =====================================================
-- Esta migration implementa a nova estrutura de roles baseada
-- nas necessidades do município:
-- - Administrador (Secretaria Municipal)
-- - Técnico (Suporte - somente leitura)
-- - Polo (Coordenador Regional)
-- - Coordenador de Escola
-- - Administrativo de Escola
-- - Professor
-- - Aluno
-- - Responsável
-- =====================================================

-- =====================================================
-- 1. CRIAR TABELA DE POLOS
-- =====================================================

CREATE TABLE IF NOT EXISTS polos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  region VARCHAR(100),
  coordinator_person_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL DEFAULT 1,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices para polos
CREATE INDEX IF NOT EXISTS idx_polos_name ON polos(name);
CREATE INDEX IF NOT EXISTS idx_polos_coordinator ON polos(coordinator_person_id);
CREATE INDEX IF NOT EXISTS idx_polos_deleted_at ON polos(deleted_at) WHERE deleted_at IS NULL;

-- Comentários para polos
COMMENT ON TABLE polos IS 'Agrupa escolas por região/distrito para gestão regional. Cada polo pode ter um coordenador responsável.';
COMMENT ON COLUMN polos.name IS 'Nome do polo (ex: Polo Norte, Polo Centro, Polo Rural).';
COMMENT ON COLUMN polos.description IS 'Descrição ou observações sobre o polo.';
COMMENT ON COLUMN polos.region IS 'Região geográfica do polo.';
COMMENT ON COLUMN polos.coordinator_person_id IS 'ID da pessoa responsável pelo polo (Coordenador Regional).';

-- Trigger para polos
CREATE TRIGGER set_polos_updated_at
  BEFORE UPDATE ON polos
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 2. ADICIONAR COLUNA polo_id NA TABELA schools
-- =====================================================

ALTER TABLE schools
  ADD COLUMN IF NOT EXISTS polo_id INTEGER;

ALTER TABLE schools
  ADD CONSTRAINT fk_schools_polo_id
  FOREIGN KEY (polo_id) REFERENCES polos(id)
  ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_schools_polo_id ON schools(polo_id);

COMMENT ON COLUMN schools.polo_id IS 'ID do polo ao qual a escola pertence.';

-- =====================================================
-- 3. ATUALIZAR ROLES EXISTENTES
-- =====================================================

-- Renomear "Coordenador" para "Polo" (Coordenador Regional)
UPDATE roles SET
  name = 'Polo',
  description = 'Coordenador Regional - supervisiona múltiplas escolas de uma região/polo'
WHERE name = 'Coordenador' AND deleted_at IS NULL;

-- Renomear "Diretor" para "Coordenador de Escola"
UPDATE roles SET
  name = 'Coordenador de Escola',
  description = 'Coordenador Pedagógico - gestão pedagógica de uma escola específica'
WHERE name = 'Diretor' AND deleted_at IS NULL;

-- Renomear "Secretário" para "Administrativo de Escola"
UPDATE roles SET
  name = 'Administrativo de Escola',
  description = 'Administrativo Escolar - matrículas, documentos, atendimento'
WHERE name = 'Secretário' AND deleted_at IS NULL;

-- =====================================================
-- 4. INSERIR NOVO ROLE: TÉCNICO
-- =====================================================

INSERT INTO roles (name, description, default_for_person_type, created_by, created_at)
VALUES (
  'Técnico',
  'Suporte Técnico - visualização de dados para suporte, sem alteração de registros',
  NULL,
  1,
  now()
) ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description;

-- =====================================================
-- 5. CRIAR NOVAS PERMISSÕES
-- =====================================================

INSERT INTO permissions (name, description, created_by, created_at) VALUES
-- Permissões de Polos
('view_polos', 'Visualizar polos', 1, now()),
('create_polos', 'Criar polos', 1, now()),
('edit_polos', 'Editar polos', 1, now()),
('delete_polos', 'Excluir polos', 1, now()),
('manage_polo_schools', 'Gerenciar escolas do polo', 1, now()),

-- Permissões de Transferência
('transfer_student_internal', 'Transferir aluno entre escolas do município', 1, now()),
('transfer_student_external', 'Transferir aluno para fora do município', 1, now()),
('approve_transfer', 'Aprovar transferências recebidas', 1, now()),

-- Permissões de Pré-Matrícula
('view_pre_enrollments', 'Visualizar pré-matrículas', 1, now()),
('approve_pre_enrollment', 'Aprovar pré-matrículas', 1, now()),
('reject_pre_enrollment', 'Rejeitar pré-matrículas', 1, now()),

-- Permissões de Rematrícula
('execute_reenrollment', 'Executar rematrícula automática', 1, now()),
('manage_reenrollment_rules', 'Configurar regras de rematrícula', 1, now()),

-- Permissões de Vagas
('view_vacancies', 'Visualizar vagas', 1, now()),
('manage_vacancies', 'Gerenciar vagas', 1, now()),

-- Permissões de Relatórios Específicos
('view_municipality_reports', 'Visualizar relatórios do município', 1, now()),
('view_polo_reports', 'Visualizar relatórios do polo', 1, now()),
('view_school_reports', 'Visualizar relatórios da escola', 1, now()),
('export_educacenso', 'Exportar dados para Educacenso', 1, now()),

-- Permissões de Auditoria
('view_audit_logs', 'Visualizar logs de auditoria', 1, now()),
('export_audit_logs', 'Exportar logs de auditoria', 1, now()),

-- Permissões de Sistema
('manage_system_settings', 'Gerenciar configurações do sistema', 1, now()),
('backup_restore', 'Fazer backup e restauração', 1, now()),

-- Permissão especial para Administrativo
('grades_with_authorization', 'Lançar notas com autorização especial', 1, now())
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- 6. CRIAR TABELA user_school_roles
-- =====================================================
-- Esta tabela vincula usuários a escolas específicas com roles específicos
-- Permite que um usuário tenha roles diferentes em escolas diferentes

CREATE TABLE IF NOT EXISTS user_school_roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id INTEGER NOT NULL,
  school_id INTEGER,
  polo_id INTEGER,
  role_id INTEGER NOT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  can_grade_with_authorization BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL DEFAULT 1,
  updated_by INTEGER,
  deleted_at TIMESTAMP,
  UNIQUE(person_id, school_id, role_id)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_user_school_roles_person_id ON user_school_roles(person_id);
CREATE INDEX IF NOT EXISTS idx_user_school_roles_school_id ON user_school_roles(school_id);
CREATE INDEX IF NOT EXISTS idx_user_school_roles_polo_id ON user_school_roles(polo_id);
CREATE INDEX IF NOT EXISTS idx_user_school_roles_role_id ON user_school_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_user_school_roles_deleted_at ON user_school_roles(deleted_at) WHERE deleted_at IS NULL;

-- Comentários
COMMENT ON TABLE user_school_roles IS 'Vincula pessoas a escolas/polos específicos com roles específicos. Permite controle granular de acesso por escola.';
COMMENT ON COLUMN user_school_roles.person_id IS 'ID da pessoa.';
COMMENT ON COLUMN user_school_roles.school_id IS 'ID da escola (NULL para roles de nível municipal/polo).';
COMMENT ON COLUMN user_school_roles.polo_id IS 'ID do polo (NULL para roles de nível municipal/escola).';
COMMENT ON COLUMN user_school_roles.role_id IS 'ID do role atribuído.';
COMMENT ON COLUMN user_school_roles.is_primary IS 'Indica se este é o vínculo principal do usuário.';
COMMENT ON COLUMN user_school_roles.can_grade_with_authorization IS 'Permissão especial para Administrativo lançar notas.';

-- Foreign Keys
ALTER TABLE user_school_roles
  ADD CONSTRAINT fk_user_school_roles_person_id
  FOREIGN KEY (person_id) REFERENCES people(id)
  ON DELETE CASCADE;

ALTER TABLE user_school_roles
  ADD CONSTRAINT fk_user_school_roles_school_id
  FOREIGN KEY (school_id) REFERENCES schools(id)
  ON DELETE CASCADE;

ALTER TABLE user_school_roles
  ADD CONSTRAINT fk_user_school_roles_polo_id
  FOREIGN KEY (polo_id) REFERENCES polos(id)
  ON DELETE CASCADE;

ALTER TABLE user_school_roles
  ADD CONSTRAINT fk_user_school_roles_role_id
  FOREIGN KEY (role_id) REFERENCES roles(id)
  ON DELETE CASCADE;

-- Trigger
CREATE TRIGGER set_user_school_roles_updated_at
  BEFORE UPDATE ON user_school_roles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 7. FUNÇÃO PARA VERIFICAR PERMISSÃO POR ESCOPO
-- =====================================================

CREATE OR REPLACE FUNCTION check_user_permission_scope(
  p_user_id UUID,
  p_permission_name VARCHAR,
  p_school_id INTEGER DEFAULT NULL,
  p_polo_id INTEGER DEFAULT NULL
)
RETURNS BOOLEAN AS $$
DECLARE
  v_person_id INTEGER;
  v_has_permission BOOLEAN := FALSE;
  v_user_role RECORD;
BEGIN
  -- Buscar person_id do usuário
  SELECT person_id INTO v_person_id
  FROM auth_users
  WHERE id = p_user_id;

  IF v_person_id IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Verificar se é Admin (acesso total)
  IF EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    WHERE ur.person_id = v_person_id
      AND r.name = 'Admin'
      AND ur.deleted_at IS NULL
      AND r.deleted_at IS NULL
  ) THEN
    RETURN TRUE;
  END IF;

  -- Verificar permissão através de user_school_roles
  FOR v_user_role IN (
    SELECT usr.*, r.name as role_name, s.polo_id as school_polo_id
    FROM user_school_roles usr
    JOIN roles r ON r.id = usr.role_id
    LEFT JOIN schools s ON s.id = usr.school_id
    WHERE usr.person_id = v_person_id
      AND usr.deleted_at IS NULL
      AND r.deleted_at IS NULL
  )
  LOOP
    -- Verificar se tem a permissão
    IF EXISTS (
      SELECT 1 FROM role_permissions rp
      JOIN permissions p ON p.id = rp.permission_id
      WHERE rp.role_id = v_user_role.role_id
        AND p.name = p_permission_name
        AND rp.deleted_at IS NULL
        AND p.deleted_at IS NULL
    ) THEN
      -- Verificar escopo
      -- Role de Polo: pode acessar escolas do seu polo
      IF v_user_role.polo_id IS NOT NULL THEN
        IF p_polo_id IS NULL OR v_user_role.polo_id = p_polo_id THEN
          IF p_school_id IS NULL THEN
            RETURN TRUE;
          ELSE
            -- Verificar se escola pertence ao polo
            IF EXISTS (
              SELECT 1 FROM schools
              WHERE id = p_school_id AND polo_id = v_user_role.polo_id
            ) THEN
              RETURN TRUE;
            END IF;
          END IF;
        END IF;
      -- Role de Escola: pode acessar apenas sua escola
      ELSIF v_user_role.school_id IS NOT NULL THEN
        IF p_school_id IS NULL OR v_user_role.school_id = p_school_id THEN
          RETURN TRUE;
        END IF;
      -- Role sem escola/polo (Técnico, Aluno, Responsável)
      ELSE
        RETURN TRUE;
      END IF;
    END IF;
  END LOOP;

  -- Verificar permissão através de user_roles (legado)
  IF EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN role_permissions rp ON rp.role_id = ur.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE ur.person_id = v_person_id
      AND p.name = p_permission_name
      AND ur.deleted_at IS NULL
      AND rp.deleted_at IS NULL
      AND p.deleted_at IS NULL
  ) THEN
    RETURN TRUE;
  END IF;

  RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION check_user_permission_scope IS 'Verifica se um usuário tem uma permissão específica, considerando o escopo (escola/polo).';

-- =====================================================
-- 8. ATUALIZAR PERMISSÕES DOS ROLES
-- =====================================================

-- Função auxiliar
CREATE OR REPLACE FUNCTION assign_permission_to_role_v2(
  p_role_name VARCHAR,
  p_permission_name VARCHAR
)
RETURNS VOID AS $$
BEGIN
  INSERT INTO role_permissions (role_id, permission_id, created_by, created_at)
  SELECT r.id, p.id, 1, now()
  FROM roles r, permissions p
  WHERE r.name = p_role_name
    AND p.name = p_permission_name
    AND r.deleted_at IS NULL
    AND p.deleted_at IS NULL
  ON CONFLICT (role_id, permission_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- ADMIN: Todas as permissões (já configurado, apenas adicionar as novas)
INSERT INTO role_permissions (role_id, permission_id, created_by, created_at)
SELECT r.id, p.id, 1, now()
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'Admin'
  AND r.deleted_at IS NULL
  AND p.deleted_at IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- TÉCNICO: Apenas visualização
SELECT assign_permission_to_role_v2('Técnico', 'view_people');
SELECT assign_permission_to_role_v2('Técnico', 'view_students');
SELECT assign_permission_to_role_v2('Técnico', 'view_teachers');
SELECT assign_permission_to_role_v2('Técnico', 'view_schools');
SELECT assign_permission_to_role_v2('Técnico', 'view_polos');
SELECT assign_permission_to_role_v2('Técnico', 'view_classes');
SELECT assign_permission_to_role_v2('Técnico', 'view_enrollments');
SELECT assign_permission_to_role_v2('Técnico', 'view_grades');
SELECT assign_permission_to_role_v2('Técnico', 'view_attendance');
SELECT assign_permission_to_role_v2('Técnico', 'view_documents');
SELECT assign_permission_to_role_v2('Técnico', 'view_communications');
SELECT assign_permission_to_role_v2('Técnico', 'view_protocols');
SELECT assign_permission_to_role_v2('Técnico', 'view_portal_content');
SELECT assign_permission_to_role_v2('Técnico', 'view_settings');
SELECT assign_permission_to_role_v2('Técnico', 'view_reports');
SELECT assign_permission_to_role_v2('Técnico', 'view_municipality_reports');
SELECT assign_permission_to_role_v2('Técnico', 'view_polo_reports');
SELECT assign_permission_to_role_v2('Técnico', 'view_school_reports');
SELECT assign_permission_to_role_v2('Técnico', 'view_audit_logs');
SELECT assign_permission_to_role_v2('Técnico', 'view_pre_enrollments');
SELECT assign_permission_to_role_v2('Técnico', 'view_vacancies');
SELECT assign_permission_to_role_v2('Técnico', 'manage_system_settings');
SELECT assign_permission_to_role_v2('Técnico', 'backup_restore');

-- POLO: Supervisão regional
SELECT assign_permission_to_role_v2('Polo', 'view_polos');
SELECT assign_permission_to_role_v2('Polo', 'edit_polos');
SELECT assign_permission_to_role_v2('Polo', 'manage_polo_schools');
SELECT assign_permission_to_role_v2('Polo', 'view_people');
SELECT assign_permission_to_role_v2('Polo', 'create_people');
SELECT assign_permission_to_role_v2('Polo', 'edit_people');
SELECT assign_permission_to_role_v2('Polo', 'view_students');
SELECT assign_permission_to_role_v2('Polo', 'create_students');
SELECT assign_permission_to_role_v2('Polo', 'edit_students');
SELECT assign_permission_to_role_v2('Polo', 'view_teachers');
SELECT assign_permission_to_role_v2('Polo', 'create_teachers');
SELECT assign_permission_to_role_v2('Polo', 'edit_teachers');
SELECT assign_permission_to_role_v2('Polo', 'view_schools');
SELECT assign_permission_to_role_v2('Polo', 'edit_schools');
SELECT assign_permission_to_role_v2('Polo', 'view_classes');
SELECT assign_permission_to_role_v2('Polo', 'create_classes');
SELECT assign_permission_to_role_v2('Polo', 'edit_classes');
SELECT assign_permission_to_role_v2('Polo', 'view_enrollments');
SELECT assign_permission_to_role_v2('Polo', 'create_enrollments');
SELECT assign_permission_to_role_v2('Polo', 'edit_enrollments');
SELECT assign_permission_to_role_v2('Polo', 'transfer_student_internal');
SELECT assign_permission_to_role_v2('Polo', 'approve_transfer');
SELECT assign_permission_to_role_v2('Polo', 'view_grades');
SELECT assign_permission_to_role_v2('Polo', 'view_attendance');
SELECT assign_permission_to_role_v2('Polo', 'view_documents');
SELECT assign_permission_to_role_v2('Polo', 'create_documents');
SELECT assign_permission_to_role_v2('Polo', 'view_communications');
SELECT assign_permission_to_role_v2('Polo', 'create_communications');
SELECT assign_permission_to_role_v2('Polo', 'view_protocols');
SELECT assign_permission_to_role_v2('Polo', 'view_reports');
SELECT assign_permission_to_role_v2('Polo', 'view_polo_reports');
SELECT assign_permission_to_role_v2('Polo', 'view_school_reports');
SELECT assign_permission_to_role_v2('Polo', 'export_reports');
SELECT assign_permission_to_role_v2('Polo', 'view_pre_enrollments');
SELECT assign_permission_to_role_v2('Polo', 'approve_pre_enrollment');
SELECT assign_permission_to_role_v2('Polo', 'reject_pre_enrollment');
SELECT assign_permission_to_role_v2('Polo', 'view_vacancies');
SELECT assign_permission_to_role_v2('Polo', 'manage_vacancies');
SELECT assign_permission_to_role_v2('Polo', 'create_users');
SELECT assign_permission_to_role_v2('Polo', 'view_portal_content');
SELECT assign_permission_to_role_v2('Polo', 'create_portal_content');
SELECT assign_permission_to_role_v2('Polo', 'edit_portal_content');
SELECT assign_permission_to_role_v2('Polo', 'publish_portal_content');

-- COORDENADOR DE ESCOLA: Gestão pedagógica
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_people');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_people');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_people');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_students');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_teachers');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_teachers');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_teachers');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_schools');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_schools');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_classes');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_classes');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_classes');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'delete_classes');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_enrollments');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_enrollments');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_grades');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_grades');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_grades');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'delete_grades');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_attendance');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_attendance');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_documents');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_documents');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_communications');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_communications');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_protocols');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_reports');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_school_reports');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'export_reports');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_portal_content');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_portal_content');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'edit_portal_content');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'publish_portal_content');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_pre_enrollments');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'approve_pre_enrollment');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'reject_pre_enrollment');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'view_vacancies');
SELECT assign_permission_to_role_v2('Coordenador de Escola', 'create_users');

-- ADMINISTRATIVO DE ESCOLA: Matrículas e documentos
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_people');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_people');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'edit_people');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_students');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_students');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'edit_students');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_teachers');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_schools');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_classes');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_enrollments');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_enrollments');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'edit_enrollments');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'transfer_student_internal');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'transfer_student_external');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'approve_transfer');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_grades');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'grades_with_authorization');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_attendance');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_documents');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_documents');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'edit_documents');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_communications');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_communications');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_protocols');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'create_protocols');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'edit_protocols');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_reports');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_school_reports');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_pre_enrollments');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'approve_pre_enrollment');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'reject_pre_enrollment');
SELECT assign_permission_to_role_v2('Administrativo de Escola', 'view_vacancies');

-- PROFESSOR: Permissões já existentes são adequadas
-- Adicionar apenas as novas permissões específicas
SELECT assign_permission_to_role_v2('Professor', 'view_school_reports');

-- ALUNO: Permissões já existentes são adequadas

-- RESPONSÁVEL: Adicionar visualização de pré-matrícula
SELECT assign_permission_to_role_v2('Responsável', 'view_pre_enrollments');

-- Remover função auxiliar
DROP FUNCTION IF EXISTS assign_permission_to_role_v2(VARCHAR, VARCHAR);

-- =====================================================
-- 9. RLS PARA POLOS
-- =====================================================

ALTER TABLE polos ENABLE ROW LEVEL SECURITY;

-- Policy para Admin ver todos
CREATE POLICY "Admin pode ver todos os polos"
  ON polos FOR SELECT
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Policy para Admin inserir
CREATE POLICY "Admin pode criar polos"
  ON polos FOR INSERT
  TO authenticated
  WITH CHECK (check_user_is_admin(auth.uid()));

-- Policy para Admin atualizar
CREATE POLICY "Admin pode editar polos"
  ON polos FOR UPDATE
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Policy para Admin excluir
CREATE POLICY "Admin pode excluir polos"
  ON polos FOR DELETE
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Policy para Coordenador de Polo ver seu polo
CREATE POLICY "Coordenador ve seu polo"
  ON polos FOR SELECT
  TO authenticated
  USING (
    coordinator_person_id = (
      SELECT person_id FROM auth_users WHERE id = auth.uid()
    )
  );

-- =====================================================
-- 10. RLS PARA user_school_roles
-- =====================================================

ALTER TABLE user_school_roles ENABLE ROW LEVEL SECURITY;

-- Policy para Admin
CREATE POLICY "Admin pode gerenciar user_school_roles"
  ON user_school_roles FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Policy para usuário ver seus próprios roles
CREATE POLICY "Usuario ve seus proprios roles"
  ON user_school_roles FOR SELECT
  TO authenticated
  USING (
    person_id = (
      SELECT person_id FROM auth_users WHERE id = auth.uid()
    )
  );

-- =====================================================
-- FIM DA MIGRATION 034
-- =====================================================
-- Resumo:
-- - Tabela polos criada
-- - Coluna polo_id adicionada em schools
-- - Roles atualizados (Coordenador->Polo, Diretor->Coordenador de Escola, Secretário->Administrativo de Escola)
-- - Role Técnico criado
-- - 25 novas permissões criadas
-- - Tabela user_school_roles criada para vincular usuários a escolas/polos
-- - Função check_user_permission_scope criada
-- - RLS configurado para polos e user_school_roles
-- =====================================================
