-- =====================================================
-- MIGRATION 035: SISTEMA DE TRANSFERÊNCIA DE ALUNOS
-- =====================================================
-- Implementa a lógica completa de transferência interna
-- entre escolas do mesmo município, preservando:
-- - Estatísticas por data de corte
-- - Histórico de notas e frequência
-- - Fluxo de aprovação pela escola destino
-- =====================================================

-- =====================================================
-- 1. CRIAR ENUM PARA STATUS DE TRANSFERÊNCIA
-- =====================================================

DO $$ BEGIN
  CREATE TYPE transfer_status AS ENUM (
    'Pendente',           -- Aguardando aprovação da escola destino
    'Aprovada',           -- Aprovada, aguardando efetivação
    'Efetivada',          -- Transferência concluída
    'Rejeitada',          -- Escola destino rejeitou
    'Cancelada'           -- Escola origem cancelou a solicitação
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE transfer_type AS ENUM (
    'Interna',            -- Entre escolas do mesmo município
    'Externa_Saida',      -- Saída para outro município/estado
    'Externa_Entrada'     -- Entrada de outro município/estado
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- =====================================================
-- 2. CRIAR TABELA DE TRANSFERÊNCIAS
-- =====================================================

CREATE TABLE IF NOT EXISTS student_transfers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Aluno
  student_profile_id INTEGER NOT NULL,

  -- Escolas
  escola_origem_id INTEGER NOT NULL,
  escola_destino_id INTEGER,  -- NULL para transferência externa de saída

  -- Matrículas
  matricula_origem_id INTEGER NOT NULL,
  matricula_destino_id INTEGER,  -- Preenchido após efetivação

  -- Tipo e Status
  transfer_type transfer_type NOT NULL DEFAULT 'Interna',
  status transfer_status NOT NULL DEFAULT 'Pendente',

  -- Datas importantes
  data_solicitacao TIMESTAMP NOT NULL DEFAULT now(),  -- DATA DE CORTE para estatísticas
  data_aprovacao TIMESTAMP,
  data_efetivacao TIMESTAMP,
  data_cancelamento TIMESTAMP,

  -- Responsáveis
  solicitante_id INTEGER NOT NULL,  -- Quem pediu a transferência
  aprovador_id INTEGER,             -- Quem aprovou/rejeitou

  -- Informações adicionais
  motivo TEXT,                      -- Motivo da transferência
  motivo_rejeicao TEXT,             -- Se rejeitada, por quê
  observacoes TEXT,

  -- Dados para transferência externa
  cidade_destino VARCHAR(100),
  estado_destino VARCHAR(2),
  escola_destino_nome VARCHAR(255),  -- Nome da escola externa

  -- Auditoria
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL DEFAULT 1,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_student_transfers_student ON student_transfers(student_profile_id);
CREATE INDEX IF NOT EXISTS idx_student_transfers_origem ON student_transfers(escola_origem_id);
CREATE INDEX IF NOT EXISTS idx_student_transfers_destino ON student_transfers(escola_destino_id);
CREATE INDEX IF NOT EXISTS idx_student_transfers_status ON student_transfers(status);
CREATE INDEX IF NOT EXISTS idx_student_transfers_type ON student_transfers(transfer_type);
CREATE INDEX IF NOT EXISTS idx_student_transfers_data_solicitacao ON student_transfers(data_solicitacao);
CREATE INDEX IF NOT EXISTS idx_student_transfers_deleted_at ON student_transfers(deleted_at) WHERE deleted_at IS NULL;

-- Comentários
COMMENT ON TABLE student_transfers IS 'Registra todas as transferências de alunos, internas e externas, com fluxo de aprovação.';
COMMENT ON COLUMN student_transfers.data_solicitacao IS 'Data de corte para estatísticas - quando o aluno "sai" da escola origem para fins de relatórios.';
COMMENT ON COLUMN student_transfers.escola_destino_id IS 'NULL para transferências externas de saída.';
COMMENT ON COLUMN student_transfers.matricula_destino_id IS 'Preenchido automaticamente quando a transferência é efetivada.';

-- Foreign Keys
ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_student
  FOREIGN KEY (student_profile_id) REFERENCES student_profiles(id);

ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_escola_origem
  FOREIGN KEY (escola_origem_id) REFERENCES schools(id);

ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_escola_destino
  FOREIGN KEY (escola_destino_id) REFERENCES schools(id);

ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_matricula_origem
  FOREIGN KEY (matricula_origem_id) REFERENCES student_enrollments(id);

ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_solicitante
  FOREIGN KEY (solicitante_id) REFERENCES people(id);

ALTER TABLE student_transfers
  ADD CONSTRAINT fk_transfers_aprovador
  FOREIGN KEY (aprovador_id) REFERENCES people(id);

-- Trigger de updated_at
CREATE TRIGGER set_student_transfers_updated_at
  BEFORE UPDATE ON student_transfers
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 3. ADICIONAR COLUNAS EM student_enrollments
-- =====================================================

-- Adicionar novo status ao ENUM existente se necessário
DO $$ BEGIN
  ALTER TYPE student_enrollment_status ADD VALUE IF NOT EXISTS 'Transferido_Interno';
  ALTER TYPE student_enrollment_status ADD VALUE IF NOT EXISTS 'Transferido_Externo';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Colunas para rastrear transferência
ALTER TABLE student_enrollments
  ADD COLUMN IF NOT EXISTS transferencia_id INTEGER,
  ADD COLUMN IF NOT EXISTS matricula_origem_id INTEGER,
  ADD COLUMN IF NOT EXISTS data_fim TIMESTAMP;

-- Foreign Keys
ALTER TABLE student_enrollments
  ADD CONSTRAINT fk_enrollments_transferencia
  FOREIGN KEY (transferencia_id) REFERENCES student_transfers(id);

ALTER TABLE student_enrollments
  ADD CONSTRAINT fk_enrollments_matricula_origem
  FOREIGN KEY (matricula_origem_id) REFERENCES student_enrollments(id);

-- Comentários
COMMENT ON COLUMN student_enrollments.transferencia_id IS 'ID da transferência que encerrou esta matrícula.';
COMMENT ON COLUMN student_enrollments.matricula_origem_id IS 'ID da matrícula anterior (em caso de transferência interna).';
COMMENT ON COLUMN student_enrollments.data_fim IS 'Data de encerramento da matrícula (transferência, conclusão, etc).';

-- Índice para busca
CREATE INDEX IF NOT EXISTS idx_enrollments_transferencia ON student_enrollments(transferencia_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_matricula_origem ON student_enrollments(matricula_origem_id);

-- =====================================================
-- 4. FUNÇÕES PARA GERENCIAR TRANSFERÊNCIAS
-- =====================================================

-- Função para solicitar transferência interna
CREATE OR REPLACE FUNCTION solicitar_transferencia_interna(
  p_student_profile_id INTEGER,
  p_escola_destino_id INTEGER,
  p_solicitante_id INTEGER,
  p_motivo TEXT DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
  v_matricula_ativa_id INTEGER;
  v_escola_origem_id INTEGER;
  v_transfer_id INTEGER;
BEGIN
  -- Buscar matrícula ativa do aluno
  SELECT id, school_id INTO v_matricula_ativa_id, v_escola_origem_id
  FROM student_enrollments
  WHERE student_profile_id = p_student_profile_id
    AND enrollment_status = 'Ativo'
    AND deleted_at IS NULL
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_matricula_ativa_id IS NULL THEN
    RAISE EXCEPTION 'Aluno não possui matrícula ativa';
  END IF;

  IF v_escola_origem_id = p_escola_destino_id THEN
    RAISE EXCEPTION 'Escola destino é a mesma da origem';
  END IF;

  -- Verificar se já existe transferência pendente
  IF EXISTS (
    SELECT 1 FROM student_transfers
    WHERE student_profile_id = p_student_profile_id
      AND status = 'Pendente'
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Já existe uma transferência pendente para este aluno';
  END IF;

  -- Criar registro de transferência
  INSERT INTO student_transfers (
    student_profile_id,
    escola_origem_id,
    escola_destino_id,
    matricula_origem_id,
    transfer_type,
    status,
    data_solicitacao,
    solicitante_id,
    motivo,
    created_by
  ) VALUES (
    p_student_profile_id,
    v_escola_origem_id,
    p_escola_destino_id,
    v_matricula_ativa_id,
    'Interna',
    'Pendente',
    now(),
    p_solicitante_id,
    p_motivo,
    p_solicitante_id
  )
  RETURNING id INTO v_transfer_id;

  RETURN v_transfer_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para aprovar transferência
CREATE OR REPLACE FUNCTION aprovar_transferencia(
  p_transfer_id INTEGER,
  p_aprovador_id INTEGER
)
RETURNS BOOLEAN AS $$
BEGIN
  -- Verificar se transferência existe e está pendente
  IF NOT EXISTS (
    SELECT 1 FROM student_transfers
    WHERE id = p_transfer_id
      AND status = 'Pendente'
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Transferência não encontrada ou não está pendente';
  END IF;

  -- Atualizar status para aprovada
  UPDATE student_transfers
  SET status = 'Aprovada',
      data_aprovacao = now(),
      aprovador_id = p_aprovador_id,
      updated_by = p_aprovador_id
  WHERE id = p_transfer_id;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para efetivar transferência (após aprovação)
CREATE OR REPLACE FUNCTION efetivar_transferencia(
  p_transfer_id INTEGER,
  p_turma_id INTEGER DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
  v_transfer RECORD;
  v_nova_matricula_id INTEGER;
  v_academic_year_id INTEGER;
  v_course_id INTEGER;
BEGIN
  -- Buscar dados da transferência
  SELECT * INTO v_transfer
  FROM student_transfers
  WHERE id = p_transfer_id
    AND status = 'Aprovada'
    AND deleted_at IS NULL;

  IF v_transfer IS NULL THEN
    RAISE EXCEPTION 'Transferência não encontrada ou não está aprovada';
  END IF;

  -- Buscar dados da matrícula origem
  SELECT academic_year_id, course_id INTO v_academic_year_id, v_course_id
  FROM student_enrollments
  WHERE id = v_transfer.matricula_origem_id;

  -- Iniciar transação de efetivação

  -- 1. Encerrar matrícula origem
  UPDATE student_enrollments
  SET enrollment_status = 'Transferido_Interno',
      transferencia_id = p_transfer_id,
      data_fim = v_transfer.data_solicitacao,  -- Usa data da solicitação como corte
      updated_at = now()
  WHERE id = v_transfer.matricula_origem_id;

  -- 2. Criar nova matrícula na escola destino
  INSERT INTO student_enrollments (
    student_profile_id,
    school_id,
    academic_year_id,
    course_id,
    enrollment_status,
    enrollment_date,
    matricula_origem_id,
    created_by
  ) VALUES (
    v_transfer.student_profile_id,
    v_transfer.escola_destino_id,
    v_academic_year_id,
    v_course_id,
    'Ativo',
    now(),
    v_transfer.matricula_origem_id,
    v_transfer.aprovador_id
  )
  RETURNING id INTO v_nova_matricula_id;

  -- 3. Enturmar se turma foi especificada
  IF p_turma_id IS NOT NULL THEN
    INSERT INTO class_enrollments (
      student_enrollment_id,
      class_id,
      enrollment_date,
      status,
      created_by
    ) VALUES (
      v_nova_matricula_id,
      p_turma_id,
      now(),
      'Ativo',
      v_transfer.aprovador_id
    );
  END IF;

  -- 4. Atualizar registro de transferência
  UPDATE student_transfers
  SET status = 'Efetivada',
      data_efetivacao = now(),
      matricula_destino_id = v_nova_matricula_id,
      updated_at = now()
  WHERE id = p_transfer_id;

  RETURN v_nova_matricula_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para rejeitar transferência
CREATE OR REPLACE FUNCTION rejeitar_transferencia(
  p_transfer_id INTEGER,
  p_aprovador_id INTEGER,
  p_motivo_rejeicao TEXT
)
RETURNS BOOLEAN AS $$
BEGIN
  UPDATE student_transfers
  SET status = 'Rejeitada',
      data_aprovacao = now(),
      aprovador_id = p_aprovador_id,
      motivo_rejeicao = p_motivo_rejeicao,
      updated_by = p_aprovador_id
  WHERE id = p_transfer_id
    AND status = 'Pendente'
    AND deleted_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transferência não encontrada ou não está pendente';
  END IF;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para cancelar transferência (pela escola origem)
CREATE OR REPLACE FUNCTION cancelar_transferencia(
  p_transfer_id INTEGER,
  p_solicitante_id INTEGER
)
RETURNS BOOLEAN AS $$
BEGIN
  UPDATE student_transfers
  SET status = 'Cancelada',
      data_cancelamento = now(),
      updated_by = p_solicitante_id
  WHERE id = p_transfer_id
    AND status IN ('Pendente', 'Aprovada')
    AND deleted_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transferência não pode ser cancelada';
  END IF;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 5. VIEWS PARA RELATÓRIOS COM DATA DE CORTE
-- =====================================================

-- View: Alunos por escola COM data de corte
-- Considera alunos transferidos até a data de corte nas estatísticas da escola origem
CREATE OR REPLACE VIEW vw_alunos_por_escola_data_corte AS
SELECT
  s.id as school_id,
  s.name as school_name,
  se.id as enrollment_id,
  sp.id as student_profile_id,
  p.first_name || ' ' || p.last_name as student_name,
  se.enrollment_status,
  se.enrollment_date as data_matricula,
  se.data_fim,
  st.data_solicitacao as data_transferencia,
  CASE
    WHEN se.enrollment_status IN ('Transferido_Interno', 'Transferido_Externo')
    THEN se.data_fim
    ELSE NULL
  END as data_corte_estatisticas,
  -- Flag para saber se deve contar nas estatísticas de uma data específica
  -- Uso: WHERE data_referencia >= data_matricula AND (data_corte_estatisticas IS NULL OR data_referencia < data_corte_estatisticas)
  CASE
    WHEN se.enrollment_status = 'Ativo' THEN TRUE
    ELSE FALSE
  END as ativo_atualmente
FROM student_enrollments se
JOIN student_profiles sp ON sp.id = se.student_profile_id
JOIN people p ON p.id = sp.person_id
JOIN schools s ON s.id = se.school_id
LEFT JOIN student_transfers st ON st.matricula_origem_id = se.id
WHERE se.deleted_at IS NULL;

COMMENT ON VIEW vw_alunos_por_escola_data_corte IS 'Lista alunos por escola com informações de data de corte para estatísticas. Use data_corte_estatisticas para filtrar relatórios históricos.';

-- View: Contagem de alunos por escola em uma data específica
CREATE OR REPLACE FUNCTION fn_contagem_alunos_escola(
  p_school_id INTEGER,
  p_data_referencia DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  total_alunos BIGINT,
  alunos_ativos BIGINT,
  alunos_transferidos BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT as total_alunos,
    COUNT(*) FILTER (
      WHERE enrollment_status = 'Ativo'
    )::BIGINT as alunos_ativos,
    COUNT(*) FILTER (
      WHERE enrollment_status IN ('Transferido_Interno', 'Transferido_Externo')
        AND data_fim > p_data_referencia
    )::BIGINT as alunos_transferidos
  FROM student_enrollments
  WHERE school_id = p_school_id
    AND enrollment_date <= p_data_referencia
    AND (data_fim IS NULL OR data_fim > p_data_referencia)
    AND deleted_at IS NULL;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_contagem_alunos_escola IS 'Retorna contagem de alunos de uma escola em uma data específica, considerando transferências.';

-- View: Frequência consolidada do aluno (todas as escolas)
CREATE OR REPLACE VIEW vw_frequencia_consolidada_aluno AS
SELECT
  sp.id as student_profile_id,
  p.first_name || ' ' || p.last_name as student_name,
  ay.id as academic_year_id,
  ay.year_name as ano_letivo,
  -- Frequência por escola
  s.id as school_id,
  s.name as school_name,
  se.enrollment_date as inicio_na_escola,
  se.data_fim as fim_na_escola,
  COUNT(a.id) as total_aulas,
  COUNT(a.id) FILTER (WHERE a.status = 'Presente') as presencas,
  COUNT(a.id) FILTER (WHERE a.status IN ('Falta', 'Falta_Justificada')) as faltas,
  ROUND(
    (COUNT(a.id) FILTER (WHERE a.status = 'Presente')::NUMERIC /
     NULLIF(COUNT(a.id), 0) * 100), 2
  ) as percentual_escola
FROM student_profiles sp
JOIN people p ON p.id = sp.person_id
JOIN student_enrollments se ON se.student_profile_id = sp.id
JOIN schools s ON s.id = se.school_id
JOIN academic_years ay ON ay.id = se.academic_year_id
LEFT JOIN attendance a ON a.student_profile_id = sp.id
  AND a.attendance_date >= se.enrollment_date
  AND (se.data_fim IS NULL OR a.attendance_date < se.data_fim)
WHERE sp.deleted_at IS NULL
  AND se.deleted_at IS NULL
GROUP BY sp.id, p.first_name, p.last_name, ay.id, ay.year_name,
         s.id, s.name, se.enrollment_date, se.data_fim;

COMMENT ON VIEW vw_frequencia_consolidada_aluno IS 'Mostra frequência do aluno separada por escola, para consolidação em relatórios.';

-- Função: Calcular frequência consolidada do aluno
CREATE OR REPLACE FUNCTION fn_frequencia_consolidada_aluno(
  p_student_profile_id INTEGER,
  p_academic_year_id INTEGER DEFAULT NULL
)
RETURNS TABLE (
  total_aulas BIGINT,
  presencas BIGINT,
  faltas BIGINT,
  percentual_geral NUMERIC,
  atinge_minimo BOOLEAN
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    SUM(v.total_aulas)::BIGINT,
    SUM(v.presencas)::BIGINT,
    SUM(v.faltas)::BIGINT,
    ROUND(
      (SUM(v.presencas)::NUMERIC / NULLIF(SUM(v.total_aulas), 0) * 100), 2
    ),
    (SUM(v.presencas)::NUMERIC / NULLIF(SUM(v.total_aulas), 0) * 100) >= 75
  FROM vw_frequencia_consolidada_aluno v
  WHERE v.student_profile_id = p_student_profile_id
    AND (p_academic_year_id IS NULL OR v.academic_year_id = p_academic_year_id);
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_frequencia_consolidada_aluno IS 'Calcula frequência consolidada do aluno somando todas as escolas do ano letivo.';

-- =====================================================
-- 6. VIEW PARA HISTÓRICO DE NOTAS COM TRANSFERÊNCIA
-- =====================================================

CREATE OR REPLACE VIEW vw_notas_historico_completo AS
SELECT
  sp.id as student_profile_id,
  p.first_name || ' ' || p.last_name as student_name,
  s.id as school_id,
  s.name as school_name,
  se.id as enrollment_id,
  se.enrollment_status,
  se.enrollment_date,
  se.data_fim,
  sub.id as subject_id,
  sub.name as subject_name,
  ap.id as period_id,
  ap.name as period_name,
  g.grade_value,
  g.created_at as data_lancamento,
  -- Flag para saber de qual escola veio a nota
  CASE
    WHEN se.enrollment_status IN ('Transferido_Interno', 'Transferido_Externo')
    THEN 'Escola Anterior'
    ELSE 'Escola Atual'
  END as origem_nota
FROM student_profiles sp
JOIN people p ON p.id = sp.person_id
JOIN student_enrollments se ON se.student_profile_id = sp.id
JOIN schools s ON s.id = se.school_id
JOIN class_enrollments ce ON ce.student_enrollment_id = se.id
JOIN classes c ON c.id = ce.class_id
JOIN class_teacher_subjects cts ON cts.class_id = c.id
JOIN subjects sub ON sub.id = cts.subject_id
LEFT JOIN grades g ON g.student_profile_id = sp.id
  AND g.subject_id = sub.id
  AND g.created_at >= se.enrollment_date
  AND (se.data_fim IS NULL OR g.created_at < se.data_fim)
LEFT JOIN academic_periods ap ON ap.id = g.academic_period_id
WHERE sp.deleted_at IS NULL
  AND se.deleted_at IS NULL;

COMMENT ON VIEW vw_notas_historico_completo IS 'Histórico completo de notas do aluno, mostrando de qual escola cada nota veio.';

-- =====================================================
-- 7. RLS PARA student_transfers
-- =====================================================

ALTER TABLE student_transfers ENABLE ROW LEVEL SECURITY;

-- Admin pode tudo
CREATE POLICY "Admin pode gerenciar transferencias"
  ON student_transfers FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Escola origem pode ver e criar suas transferências
CREATE POLICY "Escola origem pode ver suas transferencias"
  ON student_transfers FOR SELECT
  TO authenticated
  USING (
    escola_origem_id IN (
      SELECT school_id FROM user_school_roles
      WHERE person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
        AND deleted_at IS NULL
    )
  );

-- Escola destino pode ver transferências para ela
CREATE POLICY "Escola destino pode ver transferencias recebidas"
  ON student_transfers FOR SELECT
  TO authenticated
  USING (
    escola_destino_id IN (
      SELECT school_id FROM user_school_roles
      WHERE person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
        AND deleted_at IS NULL
    )
  );

-- Polo pode ver transferências das escolas do polo
CREATE POLICY "Polo pode ver transferencias do polo"
  ON student_transfers FOR SELECT
  TO authenticated
  USING (
    escola_origem_id IN (
      SELECT s.id FROM schools s
      JOIN user_school_roles usr ON usr.polo_id = s.polo_id
      WHERE usr.person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
        AND usr.deleted_at IS NULL
    )
    OR
    escola_destino_id IN (
      SELECT s.id FROM schools s
      JOIN user_school_roles usr ON usr.polo_id = s.polo_id
      WHERE usr.person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
        AND usr.deleted_at IS NULL
    )
  );

-- =====================================================
-- FIM DA MIGRATION 035
-- =====================================================
-- Resumo:
-- - ENUMs: transfer_status, transfer_type
-- - Tabela: student_transfers
-- - Colunas em student_enrollments: transferencia_id, matricula_origem_id, data_fim
-- - Funções: solicitar_transferencia_interna, aprovar_transferencia,
--           efetivar_transferencia, rejeitar_transferencia, cancelar_transferencia
-- - Views: vw_alunos_por_escola_data_corte, vw_frequencia_consolidada_aluno,
--          vw_notas_historico_completo
-- - Funções de relatório: fn_contagem_alunos_escola, fn_frequencia_consolidada_aluno
-- - RLS configurado para student_transfers
-- =====================================================
