-- =====================================================
-- MIGRATION 037: SISTEMA DE PRÉ-MATRÍCULA ONLINE
-- =====================================================
-- Implementa a lógica de pré-matrícula pelo portal público
-- permitindo que famílias solicitem vagas antes do ano letivo.
--
-- Regras:
-- - Público: qualquer situação (novos, transferências, troca)
-- - Escola: sistema sugere + família pode escolher
-- - Prioridade: 1º Vulnerabilidade, 2º Proximidade, 3º Ordem
-- - Período: configurável pelo administrador
-- - Confirmação: presencial obrigatória
-- =====================================================

-- =====================================================
-- 1. CRIAR ENUMS
-- =====================================================

DO $$ BEGIN
  CREATE TYPE pre_enrollment_status AS ENUM (
    'Pendente',           -- Aguardando análise
    'Em_Analise',         -- Sendo analisada
    'Aprovada',           -- Aprovada, aguardando comparecimento
    'Lista_Espera',       -- Sem vaga, aguardando
    'Rejeitada',          -- Rejeitada (documentação, idade, etc)
    'Confirmada',         -- Família compareceu e confirmou
    'Nao_Compareceu',     -- Família não compareceu no prazo
    'Cancelada',          -- Cancelada pela família
    'Matriculada'         -- Matrícula efetivada
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE pre_enrollment_type AS ENUM (
    'Aluno_Novo',             -- Nunca estudou no município
    'Transferencia_Externa',  -- Vindo de outro município
    'Transferencia_Interna',  -- Troca de escola no município
    'Retorno'                 -- Aluno que saiu e está voltando
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE priority_criteria AS ENUM (
    'Vulnerabilidade_Social',  -- Bolsa Família, CadÚnico
    'Proximidade',             -- Mora perto da escola
    'Ordem_Inscricao'          -- Ordem de chegada
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- =====================================================
-- 2. CRIAR TABELA DE PERÍODOS DE PRÉ-MATRÍCULA
-- =====================================================

CREATE TABLE IF NOT EXISTS pre_enrollment_periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Identificação
  name VARCHAR(100) NOT NULL,
  description TEXT,
  academic_year_id INTEGER NOT NULL,

  -- Datas
  data_inicio TIMESTAMP NOT NULL,
  data_fim TIMESTAMP NOT NULL,
  data_resultado TIMESTAMP,  -- Quando divulga resultado

  -- Configurações
  is_active BOOLEAN DEFAULT FALSE,
  permite_escolha_escola BOOLEAN DEFAULT TRUE,
  max_opcoes_escola INTEGER DEFAULT 3,
  dias_para_comparecer INTEGER DEFAULT 5,

  -- Critérios de prioridade (ordem de aplicação)
  criterios_prioridade TEXT[] DEFAULT ARRAY['Vulnerabilidade_Social', 'Proximidade', 'Ordem_Inscricao'],

  -- Estatísticas
  total_solicitacoes INTEGER DEFAULT 0,
  total_aprovadas INTEGER DEFAULT 0,
  total_lista_espera INTEGER DEFAULT 0,
  total_rejeitadas INTEGER DEFAULT 0,

  -- Auditoria
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER NOT NULL DEFAULT 1,
  updated_by INTEGER,
  deleted_at TIMESTAMP
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_pre_enrollment_periods_year ON pre_enrollment_periods(academic_year_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollment_periods_active ON pre_enrollment_periods(is_active);
CREATE INDEX IF NOT EXISTS idx_pre_enrollment_periods_dates ON pre_enrollment_periods(data_inicio, data_fim);

-- Foreign Key
ALTER TABLE pre_enrollment_periods
  ADD CONSTRAINT fk_pre_enrollment_periods_year
  FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);

COMMENT ON TABLE pre_enrollment_periods IS 'Define os períodos de pré-matrícula com suas configurações.';

-- Trigger
CREATE TRIGGER set_pre_enrollment_periods_updated_at
  BEFORE UPDATE ON pre_enrollment_periods
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 3. CRIAR TABELA DE SOLICITAÇÕES DE PRÉ-MATRÍCULA
-- =====================================================

CREATE TABLE IF NOT EXISTS pre_enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Vínculo com período
  period_id INTEGER NOT NULL,

  -- Protocolo único
  protocolo VARCHAR(20) UNIQUE NOT NULL,

  -- Tipo de solicitação
  tipo pre_enrollment_type NOT NULL DEFAULT 'Aluno_Novo',

  -- Status
  status pre_enrollment_status NOT NULL DEFAULT 'Pendente',

  -- ============ DADOS DO ALUNO ============
  aluno_nome VARCHAR(255) NOT NULL,
  aluno_data_nascimento DATE NOT NULL,
  aluno_cpf VARCHAR(14),
  aluno_certidao_nascimento VARCHAR(50),
  aluno_sexo VARCHAR(1),  -- M ou F
  aluno_cor_raca VARCHAR(20),
  aluno_deficiencia BOOLEAN DEFAULT FALSE,
  aluno_tipo_deficiencia VARCHAR(100),

  -- Escola de origem (se transferência)
  escola_origem_nome VARCHAR(255),
  escola_origem_cidade VARCHAR(100),
  escola_origem_estado VARCHAR(2),

  -- Série desejada
  serie_desejada VARCHAR(20) NOT NULL,
  turno_desejado VARCHAR(20),  -- Manhã, Tarde, Integral

  -- ============ DADOS DO RESPONSÁVEL ============
  responsavel_nome VARCHAR(255) NOT NULL,
  responsavel_cpf VARCHAR(14) NOT NULL,
  responsavel_rg VARCHAR(20),
  responsavel_telefone VARCHAR(20) NOT NULL,
  responsavel_email VARCHAR(255),
  responsavel_parentesco VARCHAR(50),  -- Pai, Mãe, Avô, etc

  -- ============ ENDEREÇO ============
  endereco_cep VARCHAR(10) NOT NULL,
  endereco_logradouro VARCHAR(255) NOT NULL,
  endereco_numero VARCHAR(20),
  endereco_complemento VARCHAR(100),
  endereco_bairro VARCHAR(100) NOT NULL,
  endereco_cidade VARCHAR(100) NOT NULL DEFAULT 'Município',
  endereco_estado VARCHAR(2) NOT NULL DEFAULT 'XX',
  endereco_latitude DECIMAL(10, 8),
  endereco_longitude DECIMAL(11, 8),

  -- ============ CRITÉRIOS DE PRIORIDADE ============
  vulnerabilidade_social BOOLEAN DEFAULT FALSE,
  nis_cadunico VARCHAR(20),  -- Número de Identificação Social
  comprovante_vulnerabilidade BOOLEAN DEFAULT FALSE,

  -- ============ PONTUAÇÃO CALCULADA ============
  pontuacao_total INTEGER DEFAULT 0,
  pontuacao_vulnerabilidade INTEGER DEFAULT 0,
  pontuacao_proximidade INTEGER DEFAULT 0,
  pontuacao_ordem INTEGER DEFAULT 0,

  -- ============ ESCOLA ALOCADA ============
  escola_alocada_id INTEGER,
  posicao_lista_espera INTEGER,

  -- ============ DATAS IMPORTANTES ============
  data_solicitacao TIMESTAMP NOT NULL DEFAULT now(),
  data_analise TIMESTAMP,
  data_aprovacao TIMESTAMP,
  data_notificacao TIMESTAMP,
  data_limite_comparecimento TIMESTAMP,
  data_comparecimento TIMESTAMP,
  data_matricula TIMESTAMP,

  -- ============ ANÁLISE ============
  analisado_por INTEGER,
  motivo_rejeicao TEXT,
  observacoes TEXT,

  -- ============ RESULTADO ============
  matricula_id INTEGER,  -- Se efetivada

  -- Auditoria
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  deleted_at TIMESTAMP
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_period ON pre_enrollments(period_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_protocolo ON pre_enrollments(protocolo);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_status ON pre_enrollments(status);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_cpf_resp ON pre_enrollments(responsavel_cpf);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_cep ON pre_enrollments(endereco_cep);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_bairro ON pre_enrollments(endereco_bairro);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_escola ON pre_enrollments(escola_alocada_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_pontuacao ON pre_enrollments(pontuacao_total DESC);

-- Foreign Keys
ALTER TABLE pre_enrollments
  ADD CONSTRAINT fk_pre_enrollments_period
  FOREIGN KEY (period_id) REFERENCES pre_enrollment_periods(id);

ALTER TABLE pre_enrollments
  ADD CONSTRAINT fk_pre_enrollments_escola
  FOREIGN KEY (escola_alocada_id) REFERENCES schools(id);

ALTER TABLE pre_enrollments
  ADD CONSTRAINT fk_pre_enrollments_matricula
  FOREIGN KEY (matricula_id) REFERENCES student_enrollments(id);

COMMENT ON TABLE pre_enrollments IS 'Armazena todas as solicitações de pré-matrícula do portal público.';

-- Trigger
CREATE TRIGGER set_pre_enrollments_updated_at
  BEFORE UPDATE ON pre_enrollments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 4. CRIAR TABELA DE PREFERÊNCIAS DE ESCOLA
-- =====================================================

CREATE TABLE IF NOT EXISTS pre_enrollment_school_choices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  pre_enrollment_id INTEGER NOT NULL,
  school_id INTEGER NOT NULL,
  ordem_preferencia INTEGER NOT NULL,  -- 1, 2, 3

  -- Distância calculada do endereço
  distancia_km DECIMAL(10, 2),
  escola_sugerida BOOLEAN DEFAULT FALSE,  -- Sistema sugeriu?

  created_at TIMESTAMP NOT NULL DEFAULT now(),

  UNIQUE(pre_enrollment_id, school_id),
  UNIQUE(pre_enrollment_id, ordem_preferencia)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_pre_enrollment_choices_pre ON pre_enrollment_school_choices(pre_enrollment_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollment_choices_school ON pre_enrollment_school_choices(school_id);

-- Foreign Keys
ALTER TABLE pre_enrollment_school_choices
  ADD CONSTRAINT fk_pre_enrollment_choices_pre
  FOREIGN KEY (pre_enrollment_id) REFERENCES pre_enrollments(id)
  ON DELETE CASCADE;

ALTER TABLE pre_enrollment_school_choices
  ADD CONSTRAINT fk_pre_enrollment_choices_school
  FOREIGN KEY (school_id) REFERENCES schools(id);

COMMENT ON TABLE pre_enrollment_school_choices IS 'Preferências de escola indicadas pela família na pré-matrícula.';

-- =====================================================
-- 5. CRIAR TABELA DE VAGAS POR ESCOLA/SÉRIE
-- =====================================================

CREATE TABLE IF NOT EXISTS school_vacancies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  school_id INTEGER NOT NULL,
  academic_year_id INTEGER NOT NULL,
  serie VARCHAR(20) NOT NULL,
  turno VARCHAR(20) NOT NULL,  -- Manhã, Tarde, Integral

  vagas_totais INTEGER NOT NULL DEFAULT 0,
  vagas_ocupadas INTEGER NOT NULL DEFAULT 0,
  vagas_reservadas INTEGER NOT NULL DEFAULT 0,  -- Reservadas para pré-matrícula
  vagas_disponiveis INTEGER GENERATED ALWAYS AS (vagas_totais - vagas_ocupadas - vagas_reservadas) STORED,

  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),

  UNIQUE(school_id, academic_year_id, serie, turno)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_school_vacancies_school ON school_vacancies(school_id);
CREATE INDEX IF NOT EXISTS idx_school_vacancies_year ON school_vacancies(academic_year_id);
CREATE INDEX IF NOT EXISTS idx_school_vacancies_serie ON school_vacancies(serie);

-- Foreign Keys
ALTER TABLE school_vacancies
  ADD CONSTRAINT fk_school_vacancies_school
  FOREIGN KEY (school_id) REFERENCES schools(id);

ALTER TABLE school_vacancies
  ADD CONSTRAINT fk_school_vacancies_year
  FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);

COMMENT ON TABLE school_vacancies IS 'Controle de vagas por escola, série e turno.';

-- Trigger
CREATE TRIGGER set_school_vacancies_updated_at
  BEFORE UPDATE ON school_vacancies
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- 6. CRIAR TABELA DE BAIRROS E ESCOLAS (para proximidade)
-- =====================================================

CREATE TABLE IF NOT EXISTS school_coverage_areas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  school_id INTEGER NOT NULL,
  bairro VARCHAR(100) NOT NULL,
  cep_inicio VARCHAR(10),
  cep_fim VARCHAR(10),
  prioridade INTEGER DEFAULT 1,  -- 1 = área principal, 2 = secundária

  created_at TIMESTAMP NOT NULL DEFAULT now(),

  UNIQUE(school_id, bairro)
);

-- Foreign Key
ALTER TABLE school_coverage_areas
  ADD CONSTRAINT fk_school_coverage_school
  FOREIGN KEY (school_id) REFERENCES schools(id);

COMMENT ON TABLE school_coverage_areas IS 'Define os bairros de abrangência de cada escola para cálculo de proximidade.';

-- =====================================================
-- 7. FUNÇÕES DE PRÉ-MATRÍCULA
-- =====================================================

-- Função para gerar protocolo único
CREATE OR REPLACE FUNCTION fn_gerar_protocolo_pre_matricula()
RETURNS VARCHAR AS $$
DECLARE
  v_ano VARCHAR(4);
  v_sequencia INTEGER;
  v_protocolo VARCHAR(20);
BEGIN
  v_ano := EXTRACT(YEAR FROM now())::VARCHAR;

  -- Buscar próxima sequência do ano
  SELECT COALESCE(MAX(
    CAST(SUBSTRING(protocolo FROM 5 FOR 6) AS INTEGER)
  ), 0) + 1
  INTO v_sequencia
  FROM pre_enrollments
  WHERE protocolo LIKE v_ano || '%';

  -- Formato: AAAA-NNNNNN (ex: 2027-000001)
  v_protocolo := v_ano || '-' || LPAD(v_sequencia::VARCHAR, 6, '0');

  RETURN v_protocolo;
END;
$$ LANGUAGE plpgsql;

-- Função para calcular pontuação de prioridade
CREATE OR REPLACE FUNCTION fn_calcular_pontuacao_pre_matricula(
  p_pre_enrollment_id INTEGER
)
RETURNS INTEGER AS $$
DECLARE
  v_pre RECORD;
  v_period RECORD;
  v_pontuacao_total INTEGER := 0;
  v_pontuacao_vulnerabilidade INTEGER := 0;
  v_pontuacao_proximidade INTEGER := 0;
  v_pontuacao_ordem INTEGER := 0;
  v_posicao_ordem INTEGER;
BEGIN
  -- Buscar pré-matrícula
  SELECT * INTO v_pre FROM pre_enrollments WHERE id = p_pre_enrollment_id;

  IF v_pre IS NULL THEN
    RETURN 0;
  END IF;

  -- Buscar período
  SELECT * INTO v_period FROM pre_enrollment_periods WHERE id = v_pre.period_id;

  -- 1. VULNERABILIDADE SOCIAL (maior peso: 1000 pontos)
  IF v_pre.vulnerabilidade_social = TRUE AND v_pre.comprovante_vulnerabilidade = TRUE THEN
    v_pontuacao_vulnerabilidade := 1000;
  END IF;

  -- 2. PROXIMIDADE (peso médio: até 500 pontos)
  -- Verifica se bairro está na área de cobertura da escola escolhida
  IF EXISTS (
    SELECT 1 FROM school_coverage_areas sca
    JOIN pre_enrollment_school_choices pesc ON pesc.school_id = sca.school_id
    WHERE pesc.pre_enrollment_id = p_pre_enrollment_id
      AND pesc.ordem_preferencia = 1
      AND LOWER(sca.bairro) = LOWER(v_pre.endereco_bairro)
  ) THEN
    -- Está na área de cobertura principal
    SELECT CASE prioridade
      WHEN 1 THEN 500  -- Área principal
      WHEN 2 THEN 300  -- Área secundária
      ELSE 100
    END INTO v_pontuacao_proximidade
    FROM school_coverage_areas sca
    JOIN pre_enrollment_school_choices pesc ON pesc.school_id = sca.school_id
    WHERE pesc.pre_enrollment_id = p_pre_enrollment_id
      AND pesc.ordem_preferencia = 1
      AND LOWER(sca.bairro) = LOWER(v_pre.endereco_bairro)
    LIMIT 1;
  END IF;

  -- 3. ORDEM DE INSCRIÇÃO (peso menor: até 100 pontos)
  -- Quanto mais cedo inscreveu, mais pontos
  SELECT COUNT(*) + 1 INTO v_posicao_ordem
  FROM pre_enrollments pe
  WHERE pe.period_id = v_pre.period_id
    AND pe.data_solicitacao < v_pre.data_solicitacao
    AND pe.deleted_at IS NULL;

  -- Máximo 100 pontos, decresce conforme posição
  v_pontuacao_ordem := GREATEST(0, 100 - v_posicao_ordem);

  -- Calcular total
  v_pontuacao_total := v_pontuacao_vulnerabilidade + v_pontuacao_proximidade + v_pontuacao_ordem;

  -- Atualizar registro
  UPDATE pre_enrollments SET
    pontuacao_vulnerabilidade = v_pontuacao_vulnerabilidade,
    pontuacao_proximidade = v_pontuacao_proximidade,
    pontuacao_ordem = v_pontuacao_ordem,
    pontuacao_total = v_pontuacao_total
  WHERE id = p_pre_enrollment_id;

  RETURN v_pontuacao_total;
END;
$$ LANGUAGE plpgsql;

-- Função para criar solicitação de pré-matrícula
CREATE OR REPLACE FUNCTION fn_criar_pre_matricula(
  p_period_id INTEGER,
  p_dados JSONB
)
RETURNS TABLE (
  pre_enrollment_id INTEGER,
  protocolo VARCHAR
) AS $$
DECLARE
  v_protocolo VARCHAR;
  v_pre_id INTEGER;
  v_escola_id INTEGER;
  v_ordem INTEGER;
BEGIN
  -- Verificar se período está ativo
  IF NOT EXISTS (
    SELECT 1 FROM pre_enrollment_periods
    WHERE id = p_period_id
      AND is_active = TRUE
      AND now() BETWEEN data_inicio AND data_fim
  ) THEN
    RAISE EXCEPTION 'Período de pré-matrícula não está aberto';
  END IF;

  -- Gerar protocolo
  v_protocolo := fn_gerar_protocolo_pre_matricula();

  -- Inserir pré-matrícula
  INSERT INTO pre_enrollments (
    period_id,
    protocolo,
    tipo,
    -- Dados do aluno
    aluno_nome,
    aluno_data_nascimento,
    aluno_cpf,
    aluno_certidao_nascimento,
    aluno_sexo,
    serie_desejada,
    turno_desejado,
    -- Escola origem
    escola_origem_nome,
    escola_origem_cidade,
    escola_origem_estado,
    -- Responsável
    responsavel_nome,
    responsavel_cpf,
    responsavel_telefone,
    responsavel_email,
    responsavel_parentesco,
    -- Endereço
    endereco_cep,
    endereco_logradouro,
    endereco_numero,
    endereco_bairro,
    endereco_cidade,
    -- Vulnerabilidade
    vulnerabilidade_social,
    nis_cadunico
  ) VALUES (
    p_period_id,
    v_protocolo,
    COALESCE((p_dados->>'tipo')::pre_enrollment_type, 'Aluno_Novo'),
    -- Dados do aluno
    p_dados->>'aluno_nome',
    (p_dados->>'aluno_data_nascimento')::DATE,
    p_dados->>'aluno_cpf',
    p_dados->>'aluno_certidao_nascimento',
    p_dados->>'aluno_sexo',
    p_dados->>'serie_desejada',
    p_dados->>'turno_desejado',
    -- Escola origem
    p_dados->>'escola_origem_nome',
    p_dados->>'escola_origem_cidade',
    p_dados->>'escola_origem_estado',
    -- Responsável
    p_dados->>'responsavel_nome',
    p_dados->>'responsavel_cpf',
    p_dados->>'responsavel_telefone',
    p_dados->>'responsavel_email',
    p_dados->>'responsavel_parentesco',
    -- Endereço
    p_dados->>'endereco_cep',
    p_dados->>'endereco_logradouro',
    p_dados->>'endereco_numero',
    p_dados->>'endereco_bairro',
    COALESCE(p_dados->>'endereco_cidade', 'Município'),
    -- Vulnerabilidade
    COALESCE((p_dados->>'vulnerabilidade_social')::BOOLEAN, FALSE),
    p_dados->>'nis_cadunico'
  )
  RETURNING id INTO v_pre_id;

  -- Inserir preferências de escola
  IF p_dados->'escolas_preferencia' IS NOT NULL THEN
    v_ordem := 0;
    FOR v_escola_id IN SELECT (jsonb_array_elements_text(p_dados->'escolas_preferencia'))::INTEGER
    LOOP
      v_ordem := v_ordem + 1;
      INSERT INTO pre_enrollment_school_choices (
        pre_enrollment_id,
        school_id,
        ordem_preferencia,
        escola_sugerida
      ) VALUES (
        v_pre_id,
        v_escola_id,
        v_ordem,
        FALSE
      );
    END LOOP;
  END IF;

  -- Calcular pontuação
  PERFORM fn_calcular_pontuacao_pre_matricula(v_pre_id);

  -- Atualizar contador do período
  UPDATE pre_enrollment_periods
  SET total_solicitacoes = total_solicitacoes + 1
  WHERE id = p_period_id;

  RETURN QUERY SELECT v_pre_id, v_protocolo;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para aprovar pré-matrícula
CREATE OR REPLACE FUNCTION fn_aprovar_pre_matricula(
  p_pre_enrollment_id INTEGER,
  p_escola_id INTEGER,
  p_analisado_por INTEGER
)
RETURNS BOOLEAN AS $$
DECLARE
  v_pre RECORD;
  v_period RECORD;
BEGIN
  -- Buscar pré-matrícula
  SELECT * INTO v_pre FROM pre_enrollments WHERE id = p_pre_enrollment_id;

  IF v_pre IS NULL OR v_pre.status != 'Pendente' THEN
    RAISE EXCEPTION 'Pré-matrícula não encontrada ou não está pendente';
  END IF;

  -- Buscar período
  SELECT * INTO v_period FROM pre_enrollment_periods WHERE id = v_pre.period_id;

  -- Verificar vagas
  IF NOT EXISTS (
    SELECT 1 FROM school_vacancies
    WHERE school_id = p_escola_id
      AND academic_year_id = v_period.academic_year_id
      AND serie = v_pre.serie_desejada
      AND vagas_disponiveis > 0
  ) THEN
    RAISE EXCEPTION 'Não há vagas disponíveis para esta série na escola selecionada';
  END IF;

  -- Reservar vaga
  UPDATE school_vacancies
  SET vagas_reservadas = vagas_reservadas + 1
  WHERE school_id = p_escola_id
    AND academic_year_id = v_period.academic_year_id
    AND serie = v_pre.serie_desejada;

  -- Atualizar pré-matrícula
  UPDATE pre_enrollments SET
    status = 'Aprovada',
    escola_alocada_id = p_escola_id,
    data_analise = now(),
    data_aprovacao = now(),
    data_notificacao = now(),
    data_limite_comparecimento = now() + (v_period.dias_para_comparecer || ' days')::INTERVAL,
    analisado_por = p_analisado_por
  WHERE id = p_pre_enrollment_id;

  -- Atualizar contador do período
  UPDATE pre_enrollment_periods
  SET total_aprovadas = total_aprovadas + 1
  WHERE id = v_pre.period_id;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para colocar em lista de espera
CREATE OR REPLACE FUNCTION fn_lista_espera_pre_matricula(
  p_pre_enrollment_id INTEGER,
  p_escola_id INTEGER,
  p_analisado_por INTEGER
)
RETURNS INTEGER AS $$
DECLARE
  v_pre RECORD;
  v_posicao INTEGER;
BEGIN
  -- Buscar pré-matrícula
  SELECT * INTO v_pre FROM pre_enrollments WHERE id = p_pre_enrollment_id;

  -- Calcular posição na lista
  SELECT COALESCE(MAX(posicao_lista_espera), 0) + 1 INTO v_posicao
  FROM pre_enrollments
  WHERE escola_alocada_id = p_escola_id
    AND serie_desejada = v_pre.serie_desejada
    AND status = 'Lista_Espera';

  -- Atualizar
  UPDATE pre_enrollments SET
    status = 'Lista_Espera',
    escola_alocada_id = p_escola_id,
    posicao_lista_espera = v_posicao,
    data_analise = now(),
    analisado_por = p_analisado_por
  WHERE id = p_pre_enrollment_id;

  -- Atualizar contador
  UPDATE pre_enrollment_periods
  SET total_lista_espera = total_lista_espera + 1
  WHERE id = v_pre.period_id;

  RETURN v_posicao;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para rejeitar pré-matrícula
CREATE OR REPLACE FUNCTION fn_rejeitar_pre_matricula(
  p_pre_enrollment_id INTEGER,
  p_motivo TEXT,
  p_analisado_por INTEGER
)
RETURNS BOOLEAN AS $$
DECLARE
  v_pre RECORD;
BEGIN
  SELECT * INTO v_pre FROM pre_enrollments WHERE id = p_pre_enrollment_id;

  UPDATE pre_enrollments SET
    status = 'Rejeitada',
    motivo_rejeicao = p_motivo,
    data_analise = now(),
    analisado_por = p_analisado_por
  WHERE id = p_pre_enrollment_id;

  UPDATE pre_enrollment_periods
  SET total_rejeitadas = total_rejeitadas + 1
  WHERE id = v_pre.period_id;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para confirmar comparecimento e efetivar matrícula
CREATE OR REPLACE FUNCTION fn_confirmar_comparecimento(
  p_pre_enrollment_id INTEGER,
  p_confirmado_por INTEGER
)
RETURNS INTEGER AS $$
DECLARE
  v_pre RECORD;
  v_period RECORD;
  v_person_id INTEGER;
  v_student_profile_id INTEGER;
  v_matricula_id INTEGER;
BEGIN
  -- Buscar pré-matrícula
  SELECT * INTO v_pre FROM pre_enrollments WHERE id = p_pre_enrollment_id;

  IF v_pre IS NULL OR v_pre.status != 'Aprovada' THEN
    RAISE EXCEPTION 'Pré-matrícula não está aprovada';
  END IF;

  -- Verificar prazo
  IF now() > v_pre.data_limite_comparecimento THEN
    -- Marcar como não compareceu
    UPDATE pre_enrollments SET
      status = 'Nao_Compareceu'
    WHERE id = p_pre_enrollment_id;

    -- Liberar vaga reservada
    SELECT * INTO v_period FROM pre_enrollment_periods WHERE id = v_pre.period_id;

    UPDATE school_vacancies
    SET vagas_reservadas = vagas_reservadas - 1
    WHERE school_id = v_pre.escola_alocada_id
      AND academic_year_id = v_period.academic_year_id
      AND serie = v_pre.serie_desejada;

    RAISE EXCEPTION 'Prazo para comparecimento expirado';
  END IF;

  -- Buscar período
  SELECT * INTO v_period FROM pre_enrollment_periods WHERE id = v_pre.period_id;

  -- Criar pessoa (aluno)
  INSERT INTO people (
    first_name,
    last_name,
    date_of_birth,
    cpf,
    type,
    created_by
  ) VALUES (
    SPLIT_PART(v_pre.aluno_nome, ' ', 1),
    SUBSTRING(v_pre.aluno_nome FROM POSITION(' ' IN v_pre.aluno_nome) + 1),
    v_pre.aluno_data_nascimento,
    COALESCE(v_pre.aluno_cpf, 'PRE-' || v_pre.protocolo),
    'Aluno',
    p_confirmado_por
  )
  RETURNING id INTO v_person_id;

  -- Criar perfil de aluno
  INSERT INTO student_profiles (
    person_id,
    created_by
  ) VALUES (
    v_person_id,
    p_confirmado_por
  )
  RETURNING id INTO v_student_profile_id;

  -- Criar matrícula
  INSERT INTO student_enrollments (
    student_profile_id,
    school_id,
    academic_year_id,
    enrollment_status,
    enrollment_date,
    serie,
    created_by
  ) VALUES (
    v_student_profile_id,
    v_pre.escola_alocada_id,
    v_period.academic_year_id,
    'Ativo',
    now(),
    v_pre.serie_desejada,
    p_confirmado_por
  )
  RETURNING id INTO v_matricula_id;

  -- Atualizar vaga (reservada -> ocupada)
  UPDATE school_vacancies
  SET vagas_reservadas = vagas_reservadas - 1,
      vagas_ocupadas = vagas_ocupadas + 1
  WHERE school_id = v_pre.escola_alocada_id
    AND academic_year_id = v_period.academic_year_id
    AND serie = v_pre.serie_desejada;

  -- Atualizar pré-matrícula
  UPDATE pre_enrollments SET
    status = 'Matriculada',
    data_comparecimento = now(),
    data_matricula = now(),
    matricula_id = v_matricula_id
  WHERE id = p_pre_enrollment_id;

  RETURN v_matricula_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para buscar escolas com vagas
CREATE OR REPLACE FUNCTION fn_buscar_escolas_com_vagas(
  p_academic_year_id INTEGER,
  p_serie VARCHAR,
  p_turno VARCHAR DEFAULT NULL,
  p_bairro VARCHAR DEFAULT NULL
)
RETURNS TABLE (
  school_id INTEGER,
  school_name VARCHAR,
  vagas_disponiveis INTEGER,
  distancia_prioridade INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    s.id as school_id,
    s.name::VARCHAR as school_name,
    sv.vagas_disponiveis,
    COALESCE(sca.prioridade, 99) as distancia_prioridade
  FROM schools s
  JOIN school_vacancies sv ON sv.school_id = s.id
  LEFT JOIN school_coverage_areas sca ON sca.school_id = s.id
    AND LOWER(sca.bairro) = LOWER(COALESCE(p_bairro, ''))
  WHERE sv.academic_year_id = p_academic_year_id
    AND sv.serie = p_serie
    AND (p_turno IS NULL OR sv.turno = p_turno)
    AND sv.vagas_disponiveis > 0
    AND s.deleted_at IS NULL
  ORDER BY distancia_prioridade ASC, sv.vagas_disponiveis DESC;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 8. VIEW PARA CONSULTA DE PRÉ-MATRÍCULAS
-- =====================================================

CREATE OR REPLACE VIEW vw_pre_matriculas AS
SELECT
  pe.id,
  pe.protocolo,
  pe.status,
  pe.tipo,
  pe.aluno_nome,
  pe.aluno_data_nascimento,
  pe.serie_desejada,
  pe.turno_desejado,
  pe.responsavel_nome,
  pe.responsavel_telefone,
  pe.responsavel_email,
  pe.endereco_bairro,
  pe.vulnerabilidade_social,
  pe.pontuacao_total,
  pe.posicao_lista_espera,
  pe.data_solicitacao,
  pe.data_limite_comparecimento,
  s.id as escola_id,
  s.name as escola_nome,
  pep.id as period_id,
  pep.name as periodo_nome,
  ay.year_name as ano_letivo
FROM pre_enrollments pe
JOIN pre_enrollment_periods pep ON pep.id = pe.period_id
JOIN academic_years ay ON ay.id = pep.academic_year_id
LEFT JOIN schools s ON s.id = pe.escola_alocada_id
WHERE pe.deleted_at IS NULL;

COMMENT ON VIEW vw_pre_matriculas IS 'Visão consolidada das pré-matrículas para listagem e consulta.';

-- View para acompanhamento público (por protocolo)
CREATE OR REPLACE VIEW vw_acompanhamento_pre_matricula AS
SELECT
  pe.protocolo,
  pe.status,
  pe.aluno_nome,
  pe.serie_desejada,
  s.name as escola_alocada,
  pe.posicao_lista_espera,
  pe.data_solicitacao,
  pe.data_aprovacao,
  pe.data_limite_comparecimento,
  CASE pe.status
    WHEN 'Pendente' THEN 'Sua solicitação está em análise'
    WHEN 'Em_Analise' THEN 'Sua solicitação está sendo analisada'
    WHEN 'Aprovada' THEN 'APROVADO! Compare à escola até ' || TO_CHAR(pe.data_limite_comparecimento, 'DD/MM/YYYY')
    WHEN 'Lista_Espera' THEN 'Em lista de espera - Posição: ' || pe.posicao_lista_espera
    WHEN 'Rejeitada' THEN 'Solicitação não aprovada: ' || pe.motivo_rejeicao
    WHEN 'Confirmada' THEN 'Matrícula confirmada!'
    WHEN 'Nao_Compareceu' THEN 'Prazo expirado - Não houve comparecimento'
    WHEN 'Matriculada' THEN 'Matrícula efetivada com sucesso!'
    ELSE 'Status desconhecido'
  END as mensagem_status
FROM pre_enrollments pe
LEFT JOIN schools s ON s.id = pe.escola_alocada_id
WHERE pe.deleted_at IS NULL;

COMMENT ON VIEW vw_acompanhamento_pre_matricula IS 'Visão pública para acompanhamento de pré-matrícula por protocolo.';

-- =====================================================
-- 9. RLS PARA TABELAS DE PRÉ-MATRÍCULA
-- =====================================================

ALTER TABLE pre_enrollment_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE pre_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE pre_enrollment_school_choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_vacancies ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_coverage_areas ENABLE ROW LEVEL SECURITY;

-- Admin pode tudo
CREATE POLICY "Admin pode gerenciar pre_enrollment_periods"
  ON pre_enrollment_periods FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

CREATE POLICY "Admin pode gerenciar pre_enrollments"
  ON pre_enrollments FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

CREATE POLICY "Admin pode gerenciar school_vacancies"
  ON school_vacancies FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

CREATE POLICY "Admin pode gerenciar school_coverage_areas"
  ON school_coverage_areas FOR ALL
  TO authenticated
  USING (check_user_is_admin(auth.uid()));

-- Períodos ativos são públicos (para o formulário)
CREATE POLICY "Periodos ativos sao publicos"
  ON pre_enrollment_periods FOR SELECT
  TO anon, authenticated
  USING (is_active = TRUE AND now() BETWEEN data_inicio AND data_fim);

-- Escola pode ver suas pré-matrículas
CREATE POLICY "Escola pode ver suas pre-matriculas"
  ON pre_enrollments FOR SELECT
  TO authenticated
  USING (
    escola_alocada_id IN (
      SELECT school_id FROM user_school_roles
      WHERE person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
        AND deleted_at IS NULL
    )
    OR
    id IN (
      SELECT pesc.pre_enrollment_id
      FROM pre_enrollment_school_choices pesc
      WHERE pesc.school_id IN (
        SELECT school_id FROM user_school_roles
        WHERE person_id = (SELECT person_id FROM auth_users WHERE id = auth.uid())
          AND deleted_at IS NULL
      )
    )
  );

-- Vagas são públicas para consulta
CREATE POLICY "Vagas sao publicas"
  ON school_vacancies FOR SELECT
  TO anon, authenticated
  USING (TRUE);

-- Áreas de cobertura são públicas
CREATE POLICY "Areas cobertura sao publicas"
  ON school_coverage_areas FOR SELECT
  TO anon, authenticated
  USING (TRUE);

-- Permitir inserção anônima de pré-matrícula (via função)
CREATE POLICY "Permitir insercao anonima de pre-matricula"
  ON pre_enrollments FOR INSERT
  TO anon
  WITH CHECK (TRUE);

CREATE POLICY "Permitir insercao anonima de escolhas"
  ON pre_enrollment_school_choices FOR INSERT
  TO anon
  WITH CHECK (TRUE);

-- =====================================================
-- FIM DA MIGRATION 037
-- =====================================================
-- Resumo:
-- - ENUMs: pre_enrollment_status, pre_enrollment_type, priority_criteria
-- - Tabelas: pre_enrollment_periods, pre_enrollments, pre_enrollment_school_choices,
--           school_vacancies, school_coverage_areas
-- - Funções:
--   - fn_gerar_protocolo_pre_matricula()
--   - fn_calcular_pontuacao_pre_matricula()
--   - fn_criar_pre_matricula()
--   - fn_aprovar_pre_matricula()
--   - fn_lista_espera_pre_matricula()
--   - fn_rejeitar_pre_matricula()
--   - fn_confirmar_comparecimento()
--   - fn_buscar_escolas_com_vagas()
-- - Views: vw_pre_matriculas, vw_acompanhamento_pre_matricula
-- - RLS configurado para todas as tabelas
-- =====================================================
