-- =====================================================
-- MIGRATION 040: ADICIONAR COLUNA course_level EM COURSES
-- =====================================================
-- Adiciona a coluna course_level para vincular cursos
-- aos níveis de ensino (education_grades)
-- =====================================================

-- 1. Adicionar coluna course_level na tabela courses
ALTER TABLE courses
  ADD COLUMN IF NOT EXISTS course_level VARCHAR(50);

COMMENT ON COLUMN courses.course_level IS 'Nível de ensino (Infantil, Fundamental I, Fundamental II, Médio, EJA)';

-- 2. Criar índice para performance
CREATE INDEX IF NOT EXISTS idx_courses_level ON courses(course_level);

-- 3. Verificar se education_grades existe, se não, criar
CREATE TABLE IF NOT EXISTS education_grades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  education_level VARCHAR(50) NOT NULL,
  grade_name VARCHAR(20) NOT NULL,
  grade_order INTEGER NOT NULL,
  is_final_grade BOOLEAN DEFAULT FALSE,
  next_grade_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE(education_level, grade_name)
);

-- 4. Índices para education_grades
CREATE INDEX IF NOT EXISTS idx_education_grades_level ON education_grades(education_level);
CREATE INDEX IF NOT EXISTS idx_education_grades_order ON education_grades(grade_order);

COMMENT ON TABLE education_grades IS 'Define as séries/anos de cada nível de ensino e a progressão entre elas.';

-- 5. Inserir séries padrão (se não existirem)
INSERT INTO education_grades (education_level, grade_name, grade_order, is_final_grade) VALUES
-- Educação Infantil (Creche)
('Infantil', 'Berçário I', 1, FALSE),
('Infantil', 'Berçário II', 2, FALSE),
('Infantil', 'Maternal I', 3, FALSE),
('Infantil', 'Maternal II', 4, FALSE),
-- Educação Infantil (Pré-escola)
('Infantil', 'Pré I', 5, FALSE),
('Infantil', 'Pré II', 6, TRUE),

-- Fundamental I (Anos Iniciais)
('Fundamental I', '1º Ano', 1, FALSE),
('Fundamental I', '2º Ano', 2, FALSE),
('Fundamental I', '3º Ano', 3, FALSE),
('Fundamental I', '4º Ano', 4, FALSE),
('Fundamental I', '5º Ano', 5, TRUE),

-- Fundamental II (Anos Finais)
('Fundamental II', '6º Ano', 1, FALSE),
('Fundamental II', '7º Ano', 2, FALSE),
('Fundamental II', '8º Ano', 3, FALSE),
('Fundamental II', '9º Ano', 4, TRUE),

-- Ensino Médio
('Médio', '1ª Série', 1, FALSE),
('Médio', '2ª Série', 2, FALSE),
('Médio', '3ª Série', 3, TRUE),

-- EJA
('EJA', 'EJA - Fase I', 1, FALSE),
('EJA', 'EJA - Fase II', 2, FALSE),
('EJA', 'EJA - Fase III', 3, FALSE),
('EJA', 'EJA - Fase IV', 4, TRUE)
ON CONFLICT (education_level, grade_name) DO NOTHING;

-- 6. Atualizar próximas séries
UPDATE education_grades SET next_grade_id = (
  SELECT id FROM education_grades g2
  WHERE g2.education_level = education_grades.education_level
    AND g2.grade_order = education_grades.grade_order + 1
);

-- 7. Habilitar RLS em education_grades
ALTER TABLE education_grades ENABLE ROW LEVEL SECURITY;

-- 8. Políticas RLS para education_grades
DROP POLICY IF EXISTS "Todos podem ver education_grades" ON education_grades;
CREATE POLICY "Todos podem ver education_grades"
  ON education_grades FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin pode gerenciar education_grades" ON education_grades;
CREATE POLICY "Admin pode gerenciar education_grades"
  ON education_grades FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM auth_users au
      WHERE au.auth_id = auth.uid()
      AND au.role IN ('Admin', 'Supervisor', 'SuperAdmin')
      AND au.deleted_at IS NULL
    )
  );

-- 9. Comentário final
COMMENT ON COLUMN courses.course_level IS 'Vincula o curso a um nível de ensino da tabela education_grades (ex: Fundamental I, Médio, etc)';

-- Fim da migration
