-- =====================================================
-- MIGRATION 041: CORRIGIR RELACIONAMENTOS ACADÊMICOS
-- =====================================================
-- Corrige as relações entre:
-- - courses (cursos/etapas de ensino)
-- - education_grades (séries/anos)
-- - classes (turmas)
-- - student_enrollments (matrículas)
-- - course_subjects (disciplinas do curso por série)
-- - evaluation_rules (regras de avaliação)
-- =====================================================

-- =====================================================
-- 1. ADICIONAR FK DE course_id EM education_grades
-- =====================================================
-- Vincula séries diretamente aos cursos

ALTER TABLE education_grades
  ADD COLUMN IF NOT EXISTS course_id INTEGER;

-- Criar FK (sem constraint para não quebrar dados existentes)
COMMENT ON COLUMN education_grades.course_id IS 'ID do curso/etapa de ensino que esta série pertence';

-- Criar índice
CREATE INDEX IF NOT EXISTS idx_education_grades_course ON education_grades(course_id);

-- =====================================================
-- 2. ADICIONAR education_grade_id EM classes
-- =====================================================
-- Permite especificar qual série/ano a turma atende

ALTER TABLE classes
  ADD COLUMN IF NOT EXISTS education_grade_id INTEGER;

-- Criar FK
ALTER TABLE classes
  DROP CONSTRAINT IF EXISTS classes_education_grade_id_fkey;

ALTER TABLE classes
  ADD CONSTRAINT classes_education_grade_id_fkey
  FOREIGN KEY (education_grade_id)
  REFERENCES education_grades(id)
  ON DELETE SET NULL;

COMMENT ON COLUMN classes.education_grade_id IS 'Série/ano específico que esta turma atende (ex: 5º Ano)';

-- Criar índice
CREATE INDEX IF NOT EXISTS idx_classes_grade ON classes(education_grade_id);

-- =====================================================
-- 3. ADICIONAR education_grade_id EM student_enrollments
-- =====================================================
-- Vincula matrícula à série específica

ALTER TABLE student_enrollments
  ADD COLUMN IF NOT EXISTS education_grade_id INTEGER;

-- Criar FK
ALTER TABLE student_enrollments
  DROP CONSTRAINT IF EXISTS student_enrollments_education_grade_id_fkey;

ALTER TABLE student_enrollments
  ADD CONSTRAINT student_enrollments_education_grade_id_fkey
  FOREIGN KEY (education_grade_id)
  REFERENCES education_grades(id)
  ON DELETE SET NULL;

COMMENT ON COLUMN student_enrollments.education_grade_id IS 'Série/ano do aluno nesta matrícula';

-- Criar índice
CREATE INDEX IF NOT EXISTS idx_enrollments_grade ON student_enrollments(education_grade_id);

-- =====================================================
-- 4. ADICIONAR education_grade_id EM course_subjects
-- =====================================================
-- Permite associar disciplinas a séries específicas

ALTER TABLE course_subjects
  ADD COLUMN IF NOT EXISTS education_grade_id INTEGER,
  ADD COLUMN IF NOT EXISTS workload_hours INTEGER,
  ADD COLUMN IF NOT EXISTS is_mandatory BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS semester INTEGER;

-- Criar FK
ALTER TABLE course_subjects
  DROP CONSTRAINT IF EXISTS course_subjects_education_grade_id_fkey;

ALTER TABLE course_subjects
  ADD CONSTRAINT course_subjects_education_grade_id_fkey
  FOREIGN KEY (education_grade_id)
  REFERENCES education_grades(id)
  ON DELETE SET NULL;

COMMENT ON COLUMN course_subjects.education_grade_id IS 'Série/ano específico onde esta disciplina é ministrada';
COMMENT ON COLUMN course_subjects.workload_hours IS 'Carga horária da disciplina em horas';
COMMENT ON COLUMN course_subjects.is_mandatory IS 'Se a disciplina é obrigatória ou optativa';
COMMENT ON COLUMN course_subjects.semester IS 'Semestre em que a disciplina é oferecida (1 ou 2, NULL para anual)';

-- Criar índice
CREATE INDEX IF NOT EXISTS idx_course_subjects_grade ON course_subjects(education_grade_id);

-- =====================================================
-- 5. CRIAR TABELA DE REGRAS DE AVALIAÇÃO
-- =====================================================

CREATE TABLE IF NOT EXISTS evaluation_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,

  -- Vínculo com curso/série
  course_id INTEGER,
  education_grade_id INTEGER,

  -- Regras de aprovação
  min_approval_grade DECIMAL(5,2) DEFAULT 7.0,
  min_attendance_percent DECIMAL(5,2) DEFAULT 75.0,

  -- Regras de avaliação
  min_evaluations_per_period INTEGER DEFAULT 2,
  max_single_evaluation_weight DECIMAL(5,2) DEFAULT 40.0,

  -- Períodos
  academic_period_type VARCHAR(20) DEFAULT 'Bimestre',
  periods_per_year INTEGER DEFAULT 4,

  -- Cálculo de média
  calculation_type VARCHAR(20) DEFAULT 'Media_Simples',
  allow_recovery BOOLEAN DEFAULT TRUE,
  recovery_replaces_lowest BOOLEAN DEFAULT TRUE,

  -- Auditoria
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by INTEGER,
  updated_by INTEGER,
  deleted_at TIMESTAMP,

  CONSTRAINT evaluation_rules_course_fkey FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  CONSTRAINT evaluation_rules_grade_fkey FOREIGN KEY (education_grade_id) REFERENCES education_grades(id) ON DELETE SET NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_evaluation_rules_course ON evaluation_rules(course_id);
CREATE INDEX IF NOT EXISTS idx_evaluation_rules_grade ON evaluation_rules(education_grade_id);
CREATE INDEX IF NOT EXISTS idx_evaluation_rules_deleted ON evaluation_rules(deleted_at) WHERE deleted_at IS NULL;

-- Comentários
COMMENT ON TABLE evaluation_rules IS 'Define as regras de avaliação por curso e/ou série (média mínima, frequência, número de avaliações, etc)';
COMMENT ON COLUMN evaluation_rules.min_approval_grade IS 'Nota mínima para aprovação (padrão: 7.0)';
COMMENT ON COLUMN evaluation_rules.min_attendance_percent IS 'Frequência mínima para aprovação em % (padrão: 75%)';
COMMENT ON COLUMN evaluation_rules.min_evaluations_per_period IS 'Número mínimo de avaliações por período';
COMMENT ON COLUMN evaluation_rules.calculation_type IS 'Tipo de cálculo: Media_Simples, Media_Ponderada, Soma_Notas';

-- RLS
ALTER TABLE evaluation_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Todos podem ver evaluation_rules" ON evaluation_rules;
CREATE POLICY "Todos podem ver evaluation_rules"
  ON evaluation_rules FOR SELECT
  USING (deleted_at IS NULL);

DROP POLICY IF EXISTS "Admin pode gerenciar evaluation_rules" ON evaluation_rules;
CREATE POLICY "Admin pode gerenciar evaluation_rules"
  ON evaluation_rules FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- =====================================================
-- 6. VINCULAR education_grade_id EM evaluation_instances
-- =====================================================
-- Permite vincular avaliações diretamente à série

ALTER TABLE evaluation_instances
  ADD COLUMN IF NOT EXISTS education_grade_id INTEGER,
  ADD COLUMN IF NOT EXISTS academic_period_id INTEGER;

-- FKs
ALTER TABLE evaluation_instances
  DROP CONSTRAINT IF EXISTS evaluation_instances_education_grade_id_fkey;

ALTER TABLE evaluation_instances
  ADD CONSTRAINT evaluation_instances_education_grade_id_fkey
  FOREIGN KEY (education_grade_id)
  REFERENCES education_grades(id)
  ON DELETE SET NULL;

ALTER TABLE evaluation_instances
  DROP CONSTRAINT IF EXISTS evaluation_instances_academic_period_id_fkey;

ALTER TABLE evaluation_instances
  ADD CONSTRAINT evaluation_instances_academic_period_id_fkey
  FOREIGN KEY (academic_period_id)
  REFERENCES academic_periods(id)
  ON DELETE SET NULL;

COMMENT ON COLUMN evaluation_instances.education_grade_id IS 'Série/ano para filtrar avaliações';
COMMENT ON COLUMN evaluation_instances.academic_period_id IS 'Período acadêmico (bimestre/trimestre) da avaliação';

-- Índices
CREATE INDEX IF NOT EXISTS idx_evaluation_instances_grade ON evaluation_instances(education_grade_id);
CREATE INDEX IF NOT EXISTS idx_evaluation_instances_period ON evaluation_instances(academic_period_id);

-- =====================================================
-- 7. INSERIR REGRAS DE AVALIAÇÃO PADRÃO
-- =====================================================

INSERT INTO evaluation_rules (
  name,
  description,
  min_approval_grade,
  min_attendance_percent,
  min_evaluations_per_period,
  academic_period_type,
  periods_per_year,
  calculation_type,
  created_by
) VALUES
(
  'Regra Padrão - Educação Infantil',
  'Avaliação descritiva sem nota numérica',
  0.0,
  60.0,
  0,
  'Bimestre',
  4,
  'Descritiva',
  1
),
(
  'Regra Padrão - Fundamental I',
  'Média 7.0, mínimo 75% frequência, 2 avaliações por bimestre',
  7.0,
  75.0,
  2,
  'Bimestre',
  4,
  'Media_Simples',
  1
),
(
  'Regra Padrão - Fundamental II',
  'Média 7.0, mínimo 75% frequência, 3 avaliações por bimestre',
  7.0,
  75.0,
  3,
  'Bimestre',
  4,
  'Media_Simples',
  1
),
(
  'Regra Padrão - Ensino Médio',
  'Média 7.0, mínimo 75% frequência, 3 avaliações por bimestre',
  7.0,
  75.0,
  3,
  'Bimestre',
  4,
  'Media_Ponderada',
  1
),
(
  'Regra Padrão - EJA',
  'Média 5.0, mínimo 75% frequência, 2 avaliações por semestre',
  5.0,
  75.0,
  2,
  'Semestre',
  2,
  'Media_Simples',
  1
)
ON CONFLICT DO NOTHING;

-- =====================================================
-- 8. VIEW PARA ESTRUTURA CURRICULAR COMPLETA
-- =====================================================

DROP VIEW IF EXISTS vw_curriculum_structure;
CREATE OR REPLACE VIEW vw_curriculum_structure AS
SELECT
  c.id as course_id,
  c.name as course_name,
  c.education_level,
  eg.id as grade_id,
  eg.grade_name,
  eg.grade_order,
  eg.is_final_grade,
  s.id as subject_id,
  s.name as subject_name,
  cs.workload_hours,
  cs.is_mandatory,
  er.name as evaluation_rule_name,
  er.min_approval_grade,
  er.min_attendance_percent
FROM courses c
LEFT JOIN education_grades eg ON eg.education_level::text = c.education_level::text
  OR eg.course_id = c.id
LEFT JOIN course_subjects cs ON cs.course_id = c.id
  AND (cs.education_grade_id = eg.id OR cs.education_grade_id IS NULL)
LEFT JOIN subjects s ON s.id = cs.subject_id
LEFT JOIN evaluation_rules er ON er.course_id = c.id
  OR er.education_grade_id = eg.id
WHERE c.deleted_at IS NULL
ORDER BY c.name, eg.grade_order, s.name;

COMMENT ON VIEW vw_curriculum_structure IS 'Visão consolidada da estrutura curricular: cursos, séries, disciplinas e regras de avaliação';

-- =====================================================
-- 9. FUNÇÃO PARA BUSCAR SÉRIE DO ALUNO
-- =====================================================

CREATE OR REPLACE FUNCTION fn_get_student_grade_info(p_enrollment_id INTEGER)
RETURNS TABLE (
  enrollment_id INTEGER,
  student_name TEXT,
  course_name VARCHAR,
  grade_name VARCHAR,
  grade_order INTEGER,
  school_name VARCHAR
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    se.id as enrollment_id,
    CONCAT(p.first_name, ' ', p.last_name) as student_name,
    c.name as course_name,
    eg.grade_name,
    eg.grade_order,
    sch.name as school_name
  FROM student_enrollments se
  JOIN student_profiles sp ON sp.id = se.student_profile_id
  JOIN people p ON p.id = sp.person_id
  JOIN schools sch ON sch.id = se.school_id
  LEFT JOIN education_grades eg ON eg.id = se.education_grade_id
  LEFT JOIN classes cl ON cl.id = (
    SELECT class_id FROM class_enrollments
    WHERE student_enrollment_id = se.id
    AND deleted_at IS NULL
    LIMIT 1
  )
  LEFT JOIN courses c ON c.id = cl.course_id
  WHERE se.id = p_enrollment_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_get_student_grade_info IS 'Retorna informações da série/ano de uma matrícula específica';

-- =====================================================
-- FIM DA MIGRATION
-- =====================================================
